\newpage

Gemeente `r df.top20.plus.unknown$gm_naam[i]`
-----------------
The table shows the speed test analysis for gemeente `r df.top20.plus.unknown$gm_naam[i]`. For this test the confidence level is set to `r 100*conflevel`%.

``` {r echo=FALSE, cache=FALSE, results='asis'}

# create temp df
# filter specific gemeente
df.tmp <- subset(df.4G.plus.hotspots,gm_naam == df.top20.plus.unknown$gm_naam[i])

# do test result use sourced function
df.tr.dwnload.g <- fn.ttest(df.tmp,"download_kbps",conflevel)
df.tr.upload.g <- fn.ttest(df.tmp,"upload_kbps",conflevel)
df.tr.latency.g <- fn.ttest(df.tmp,"latency",conflevel)

# print test result 
print(xtable(df.tr.dwnload.g,format = "pandoc" ,  caption = "Comparison of means for metric: download(kbps)",row.names=FALSE, booktabs=TRUE), size="\\footnotesize",include.rownames=FALSE,comment=FALSE)
print(xtable(df.tr.upload.g,format = "pandoc" ,  caption = "Comparison of means for metric: upload(kbps)",row.names=FALSE), size="\\footnotesize",include.rownames=FALSE,comment=FALSE)
print(xtable(df.tr.latency.g,format = "pandoc",  caption = "Comparison of means for metric: latency(ms)",row.names=FALSE), size="\\footnotesize",include.rownames=FALSE,comment=FALSE)

```



Please note the column [Sign.] or "Significant", if this column states "No" the test is not significant at the `r 100*conflevel`% confidence level. This means there is no significant difference in means observed so the NULL Hypothesis can not be rejected. In layman's terms: You can *not conclude* that one operator has a faster 4G network then the other.

**Explanation of terms**

\footnotesize

**Sample 1** : Number of speedtest samples for operator 1.

**Sample 2** : Number of speedtest samples for operator 2.

**Mean 1** : Average speed of speedtests for operator 1 in KBps. A Higher number here means that this operator has a fast download(or upload) speed. For the latency a higher number means you have to wait longer contact webpages.

**Mean 2** : Average speed of speedtests for operator 2 in KBps. A Higher number here means that this operator has a fast download(or upload) speed. For the latency a higher number means you have to wait longer contact webpages.

**P-value** : The test statistic, for more explanation see the paragraph P-Value above

**Sign.** : Short for Significance. We compare the test statistic with the predefined confidence level(`r conflevel`). 'Yes' means the test is significant, 'No' means the test is not significant."))

**Diff(in Kbps or ms)** : Difference of the means (DoM) is the difference of Mean 1 and Mean 2(Mean 1 - Mean 2). For download and upload speeds(Kbps) big positive number here means operator 1 has a faster speed then operator 2. A big negative number means that operator 2 has a faster speed then operator 1. For latency(ms) this is the opposite, because smaller is better.

**Conf Int** : Confidence interval consist of a range of values (interval) that act as good estimate of the *true* difference of the mean. We are `r 100*conflevel`% confident that the true value of the difference of the mean is in our confidence interval.

**Rel(%)** : Relative difference in percentage. It is calculated as the difference of the means divided by the slower of the two operators average speed.

\normalsize