\documentclass[]{article}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\usepackage{graphicx}

% Proper A4 geometry:
\usepackage[hmargin=2.5cm,vmargin=2.5cm,paper=a4paper]{geometry}
\usepackage{lastpage} % for the number of the last page in the document

% fancy header
\usepackage{fancyhdr}
\pagestyle{fancy}

% header content
\lhead{\includegraphics[width=0.15\textwidth]{./img/dikw-logo.png}}
\chead{Speedtest Analysis of 4G Mobile Networks}
\rhead{}

% footer
\renewcommand{\footrulewidth}{0.5pt}
%\lfoot{left footer content}
\cfoot{\tiny The analysis was performed by DIKW Consulting on behalf of T-Mobile, based on Ookla's NetMetrics Data from Speedtest.net \newline
\normalsize Page \thepage\ of \pageref{LastPage}}
%\rfoot{right footer content}

% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
    \usepackage{xltxtra,xunicode}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Mapping=tex-text,Scale=MatchLowercase}
  \newcommand{\euro}{€}
\fi

% use microtype if available
\IfFileExists{microtype.sty}{\usepackage{microtype}}{}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{{#1}}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{{#1}}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{{#1}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{{#1}}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{{#1}}}
\newcommand{\RegionMarkerTok}[1]{{#1}}
\newcommand{\ErrorTok}[1]{\textbf{{#1}}}
\newcommand{\NormalTok}[1]{{#1}}
\usepackage{longtable,booktabs}

\usepackage{graphicx}
% Redefine \includegraphics so that, unless explicit options are
% given, the image width will not exceed the width of the page.
% Images get their normal width if they fit onto the page, but
% are scaled down if they would overflow the margins.
\makeatletter
\def\ScaleIfNeeded{%
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother
\let\Oldincludegraphics\includegraphics
{%
 \catcode`\@=11\relax%
 \gdef\includegraphics{\@ifnextchar[{\Oldincludegraphics}{\Oldincludegraphics[width=\ScaleIfNeeded]}}%
}%

\ifxetex
  \usepackage[setpagesize=false, % page size defined by xetex
              unicode=false, % unicode breaks when used with xetex
              xetex]{hyperref}
\else
  \usepackage[unicode=true]{hyperref}
\fi
\hypersetup{breaklinks=true,
            bookmarks=true,
            pdfauthor={Hugo Koopmans},
            pdftitle={Independent Speed test Analysis of 4G Mobile Networks Performed by DIKW Consulting},
            colorlinks=true,
            citecolor=blue,
            urlcolor=blue,
            linkcolor=magenta,
            pdfborder={0 0 0}}
\urlstyle{same}  % don't use monospace font for urls
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\setcounter{secnumdepth}{5}

%\includegraphics[width=0.15\textwidth]{./img/dikw-logo.png} ~\\[1cm]
\title{Independent Speed test Analysis of 4G Mobile Networks Performed by DIKW
Consulting}
\author{Hugo Koopmans}
\date{17-04-2015}

% Definition of \maketitle
\makeatletter         
\def\@maketitle{
%\raggedright
\begin{center}
\includegraphics[width = 75mm]{./img/dikw-logo.png} \\[5cm]
{\Large  \@title }\\[4ex] 
{\@author}\\[4ex] 
\@date\\[8ex]
\end{center}}
\makeatother

\begin{document}
\maketitle

\newpage


{
\hypersetup{linkcolor=black}
\setcounter{tocdepth}{2}
\tableofcontents
}

\newpage

\newpage

\subsection{Colophon}\label{colophon}

This analysis is performed by DIKW Consulting.

DIKW Consulting is a consulting firm that takes her customers on the
path from Data to information to Knowledge to Wisdom. Our expertise is
in the field of data logistics, data warehousing, data mining and
machine learning.

T-Mobile has asked DIKW Consulting to perform this test as an
independent third party. DIKW Consulting was paid to perform this test
by T-mobile and has no other intentions then to perform this test by
it's own high quality standards. The analysis was performed by generally
accepted and approved standards and statistical methods using open
source tools.

We let the data speak for itself.

If you have questions you can contact \href{http://www.dikw.nl}{DIKW
Consulting}. If you want to repeat this test by yourself you are welcome
to do so, all necessary scripts are available on GitHub. The data is
commercially available at \href{http://www.ookla.com/}{Ookla}.

This analysis, method, tools and scripts are open sourced and placed on
GitHub, see the read-me on the GitHub
\href{https://github.com/hugokoopmans/ookla-speedtest-analysis}{repository}.

For questions contact Hugo Koopmans at
\href{mailto:hugo.koopmans@dikw.com}{hugo.koopmans@dikw.com} or +31 6
43106780

\subsection{Code generation}\label{code-generation}

This is an R Markdown document. Markdown is a simple formatting syntax
for authoring HTML, PDF, and MS Word documents. For more details on
using R Markdown see \url{http://rmarkdown.rstudio.com}.

\newpage

\section{Abstract}\label{abstract}

In this document we have conducted a statistical analysis of Ookla's
NetMetrics data from speedtest.net. Ookla provides commercially
available speed test data collected by their mobile app on the three
main mobile platforms, Android, iOS and Windows mobile. We will load all
the raw speed test data into a database, analyse the data ot the top
three operators(T-Mobile, Vodafone and KPN) and perform a test on how
fast their respective 4G networks are. Our test will be on download
speed, upload speed and latency(or ping).

The speed test data that is provided by Ookla's NetMetrics data from
speedtest.net and obtained by T-Mobile is of January, February and March
2015. We will analyse and validate the data step by step. After
investigation on suspicious testing circumstances, such as, but not
limited to, devices, location, theoretical maximum speeds and specific
dates the data is ready to be subjected to a significance test. This
test will be done for all the data in the coverage area and for the
biggest twenty cities in the Netherlands.

The result of these tests will give an answer to whether or not T-Mobile
has on average a faster 4G network than Vodafone and/or KPN, based on
the three metrics upload speed, download speed and latency.

\newpage

\section{Introduction}\label{introduction}

This document is a report of a statistical analysis of 4G network speed
test data. The time period we consider is Q1 2015 so the months January,
February and March of 2015 are in scope. We perform an analysis of
\href{http://www.ookla.com/}{Ookla} NetMetrics Data data on three
different measures:

\begin{itemize}
\itemsep1pt\parskip0pt\parsep0pt
\item
  download speed
\item
  upload speed
\item
  latency(or ping)
\end{itemize}

On these metrics we compare the three major providers of 4G mobile
networks in the Netherlands, Vodafone, KPN and T-Mobile.

This analysis is set up as follows:

\begin{itemize}
\itemsep1pt\parskip0pt\parsep0pt
\item
  Step 1: Data Collection
\item
  Step 2: Data preprocessing
\item
  Step 3: Data analysis
\item
  Step 4: Test design
\item
  Step 5: Test results coverage area
\end{itemize}

In section 8 we provide the conclusion, and additionally the analysis
and results of the Top 20 cities per city is presented in section 9.

\section{Step 1 : Data Collection}\label{step-1-data-collection}

The data was downloaded from Ookla servers by T-Mobile. For this
analysis we use a PostgreSQL database that is locally installed.

The data is loaded from three different files, each file resembling a
mobile platform (Android,iPhone and Windows mobile). The data is loaded
as-is as it was received from the Ookla server. Scripts to load this
data directly into a PostgreSQL database can be found in the GitHub
repository.

All scripts to process the data are in SQL(available on GitHub) or
R(included in this document, thanks to
\href{http://yihui.name/knitr/}{knitr})

Let's get the data and do some basic counts.

\subsection{The raw data}\label{the-raw-data}

We load the raw files, downloaded from the Ookla server, into individual
tables per mobile platform. In the table below we count the number of
speed tests per mobile platform in Q1/2015.

\begin{longtable}[c]{@{}lr@{}}
\toprule\addlinespace
& Counts
\\\addlinespace
\midrule\endhead
Android & 156577
\\\addlinespace
iOS & 119648
\\\addlinespace
Windows & 6998
\\\addlinespace
Sum & 283223
\\\addlinespace
\bottomrule
\addlinespace
\caption{Raw test data counts}
\end{longtable}

\newpage
So we start this analysis with in total 283223 speed tests, which are
represented as rows in the data set commercially downloaded from Ookla.

\subsection{Speedtest.net data}\label{speedtest.net-data}

Ookla designed their speed test in such a way that the results are as
robust as possible. Ookla's speedtest.net is the de-facto standard for
internet speed testing. According to
\url{http://www.ookla.com/netmetrics}, NetMetrics is the choice of
nearly every Fortune 500 ISP and Mobile Provider in the world. For more
information please visit
\href{https://support.speedtest.net/hc/en-us}{Speeedtest.net}.

\subsection{Sample test data from
Ookla}\label{sample-test-data-from-ookla}

Ookla has some random sample data available, this data can be used to
validate our method. To validate the test result one would need the
specific data of the Netherlands.

A sample set of Ookla NetMetrics data can be found
\href{http://www.ookla.com/netmetrics}{here}. The files differ per
mobile platform. The file descriptors for all three mobile platforms are
listed below.

\subsubsection{Android header
descriptives}\label{android-header-descriptives}

\footnotesize

\begin{verbatim}
test_id - unique id of test in our system
device_id - unique device id in our system
android_fingerprint
test_date - YYYY-MM-DD HH:MM:SS in Pacific time (we can accommodate different time zones if needed)
client_ip - ip of client
download_kbps - download speed in kilobits per second
upload_kbps - upload speed in kilobits per second
latency_ms - ping in milliseconds
server_name - name of server tested to (name of city it is located in)
server_country - country name of server
server_country_code - country code of server
server_latitude - latitude of server tested to
server_longitude - longitude of server tested to
server_sponsor_name - sponsor name of server
client_country - country name of the client
client_country_code - country code of the client
client_region - region name of client (this will be state in the US)
client_region_code - region code of client
client_city - city of client
client_latitude - latitude of client (GPS or Maxmind when location services disabled)
client_longitude - longitude of client (GPS or Maxmind when location services disabled)
miles_between - miles between the client and the server tested to
connection_type - http://developer.android.com/reference/android/telephony/TelephonyManager.html
   0=unknown,1= Cell, 2=Wifi, 3=Gprs, 4=Edge, 5=Utms, 6=Cdma, 7=Evdo0, 8=EvdoA, 9=OnexRTT, 
   10=Hsdpa, 11=Hspa, 12=Iden, 13=Ehrpd, 14=EvdoB, 15=Lte, 16=Hsupa, 17=Hspap
isp_name  - name of ISP (Maxmind)
is_isp    - 0=Corporation/Academic, 1=ISP
network_operator_name - Mobile Carrier Name http://developer.android.com/reference/android
   /telephony/TelephonyManager.html#getNetworkOperatorName()
network_operator_code - MCC + MNC  http://developer.android.com/reference/android
   /telephony/TelephonyManager.html#getNetworkOperator() 
brand - http://developer.android.com/reference/android/os/Build.html#BRAND 
device - http://developer.android.com/reference/android/os/Build.html#DEVICE 
hardware - http://developer.android.com/reference/android/os/Build.html#HARDWARE 
build_id - http://developer.android.com/reference/android/os/Build.html#ID 
manufacturer - http://developer.android.com/reference/android/os/Build.html#MANUFACTURER 
model - http://developer.android.com/reference/android/os/Build.html#MODEL 
product - http://developer.android.com/reference/android/os/Build.html#PRODUCT  
cdma_cell_id - http://developer.android.com/reference/android/telephony/cdma/package-summary.html 
gsm_cell_id - http://developer.android.com/reference/android/telephony/gsm/package-summary.html 
location_type - 0 = unknown, 1 = GPS, 2 = GeoIP
sim_network_operator_name - Mobile Carrier Name from the SIM
sim_network_operator_code - MCC + MNC from the SIM  http://en.wikipedia.org/wiki/Mobile_Country_Code 
\end{verbatim}

\normalsize

\subsubsection{iOS header descriptives}\label{ios-header-descriptives}

\footnotesize

\begin{verbatim}
test_id - unique id of test in our system
device_id - unique device id in our system
test_date - YYYY-MM-DD HH:MM:SS in Pacific time (we can accommodate different time zones if needed)
client_ip - ip of client 
download_kbps - download speed in kilobits per second
upload_kbps - upload speed in kilobits per second
latency_ms - ping in milliseconds
server_name - name of server tested to (name of city it is located in)
server_country - country name of server
server_country_code - country code of server
server_latitude - latitude of server tested to
server_longitude - longitude of server tested to
server_sponsor_name - sponsor name of server
client_country - country name of the client
client_country_code - country code of the client
client_region - region name of client (this will be state in the US)
client_region_code - region code of client
client_city - city of client
client_latitude - latitude of client (GPS or Maxmind when location services disabled)
client_longitude - longitude of client (GPS or Maxmind when location services disabled)
miles_between - miles between the client and the server tested to
connection_type - 0=unknown, 1=cell, 2=wifi, 3=GPRS, 4=Edge, 5=WCDMA, 6=HSDPA, 
   7=HSUPA, 8=CDMA1x, 9=CDMAEVDORev0, 10=CDMAEVDORevB, 11=eHRPD, 12=LTE 
isp_name  - name of ISP (Maxmind) 
is_isp    - 0=Corporation/Academic, 1=ISP
carrier_name - http://developer.apple.com/library/ios/documentation/NetworkingInternet
   /Reference/CTCarrier/Reference/Reference.html#//apple_ref/occ/instp/CTCarrier/carrierName 
iso_country_code - http://developer.apple.com/library/ios/documentation/NetworkingInternet
   /Reference/CTCarrier/Reference/Reference.html#//apple_ref/occ/instp/CTCarrier/isoCountryCode 
mobile_country_code - http://developer.apple.com/library/ios/documentation/NetworkingInternet
   /Reference/CTCarrier/Reference/Reference.html#//apple_ref/occ/instp/CTCarrier/mobileCountryCode 
mobile_network_code - http://developer.apple.com/library/ios/documentation/NetworkingInternet
   /Reference/CTCarrier/Reference/Reference.html#//apple_ref/occ/instp/CTCarrier/mobileNetworkCode
model - iPad, iPhone, iPod Touch 
version - iOS version
location_type - 0 = unknown, 1 = GPS, 2 = GeoIP
\end{verbatim}

\normalsize

\subsubsection{Windows Mobile header
descriptives}\label{windows-mobile-header-descriptives}

\footnotesize

\begin{verbatim}
test_id - unique id of test in our system
device_id - unique device id in our system
test_date - YYYY-MM-DD HH:MM:SS in Pacific time (we can accommodate different timezones if needed)
client_ip - ip of client 
download_kbps - download speed in kilobits per second
upload_kbps - upload speed in kilobits per second
latency_ms - ping in milliseconds
server_name - name of server tested to (name of city it is located in)
server_country - country name of server
server_country_code - country code of server
server_latitude - latitude of server tested to
server_longitude - longitude of server tested to
server_sponsor_name - sponsor name of server
client_country - country name of the client
client_country_code - country code of the client
client_region - region name of client (this will be state in the US)
client_region_code - region code of client
client_city - city of client
client_latitude - latitude of client (GPS or Maxmind when location services disabled)
client_longitude - longitude of client (GPS or Maxmind when location services disabled)
miles_between - miles between the client and the server tested to
connection_type - 0=unknown, 1=cell, 2=wifi, 3=GPRS, 4=1XRTT, 5=EVDO, 6=EDGE, 7=3G, 
   8=HSPA, 9=EVDV, 10=PassThru, 11=LTE, 12=EHRPD
isp_name  - name of ISP (Maxmind) 
is_isp    - 0=Corporation/Academic, 1=ISP
carrier_name - AT&T, Verizon etc 
manufacturer - Nokia, HTC, etc.
device_name - name of the device for e.g. "HD7 T9292" 
hardware_version - device hardware version e.g. "1.0.0.0"
firmware_version - device firmware_version e.g. "1232.2107.1241.1001"
location_type - 0 = unknown, 1 = GPS, 2 = GeoIP
\end{verbatim}

\normalsize

\section{Step 2: Data preprocessing}\label{step-2-data-preprocessing}

In order to compare the data from the three different mobile platforms,
we need to perform basic data transformations and merge it into one
table.

Following that, in this preprocessing and analysis step we validate the
data on the following points: 1. Are there any specific individual
devices that perform a suspiciously high number of tests? 2. We apply
filters so only the tests from the three operators we are interested in
remain. 3. We apply filters so only tests done on 4G technology remain.
4. We are only interested in the coverage area in which all three
operators claim to have 4G coverage. 5. We look at speed test results
that are ``too good to be true'' that is, measured speeds that are above
the theoretical maximum possible for that specific technology. We remove
these speed tests. 6. We look at specific coordinates that are very
frequent, depending on the explanation as for why these coordinates are
used to often we remove or delete the speed tests per coordinate. 7. We
look at specific dates that have a high number of speed tests for that
day.

After all these checks we end up with a data set that is cleaned and
ready to perform a statistical significance test on the investigated
metrics.

\subsection{Basic data
transformations}\label{basic-data-transformations}

As explained in section 3.3., the data from the three different mobile
platforms comes in different formats and some basic data transformations
are necessary before we can merge it into one table.

First of all, the names for the individual operators are spelled in
various ways (e.g. `T-Mobile NL`, `T-Mobile NL'). Next, we need to map
connection types to the specific technology used (2G, 3G or 4G)
depending on the operating system of the device. For more details on
these transformations, please see the SQL script on GitHub.

After these transformations are performed, we proceed with the checks
and cleaning steps explained at in the previous section.

\subsection{Suspicious devices}\label{suspicious-devices}

Are there any devices that perform tests very frequently?

In order to investigate this, let's look at a frequency plot of devices
that occur at least \textbf{ten} times in each month. On the right hand
side we see devices that are used for testing very often, some of them
even on an hourly basis. Obviously those devices are not in the hands of
real customers so these will be removed from the data set.

\includegraphics{speedtest-analysis-Q1-2015_files/figure-latex/freq-plot-devices-1.pdf}

Based on these plots and the amount of data consumed when performing a
speedtest, we decide to remove specific devices that test more than 30
times a month. These devices are probably used by telecom professionals
for testing purposes. The amount of data consumed per speedtest depends
on the speed: the higher the speed, the more data is consumed. A test on
4G at very high speed can cost up to 100 MBytes per test out of the data
bundle. So, 30 or more tests per month at high speed are equivalent to
approximately 3GB of data usage just spend on tests alone and that is
suspicious. The number 30 by itself is subjective, we could use 25 or 40
depending on what exact number of tests per device you would call
suspicious.

Actually including these are not influencing the results significantly,
but we want to use real customer data as much as possible, not affected
by professionals testing their own (or others) network.

We identify 97 devices in January, 99 devices in February and 115
devices in March, which in total represent 37574 speed tests. After
filtering these devices the data set has 283223-37574=245649 speed test
cases.

\subsection{Top three operators}\label{top-three-operators}

For this analysis we are only interested in the top three operators in
the Netherlands. In the data set, at this point, there are 806 different
operators identified. As we can see in the table below, in which we
ranked the ten most used operators, most of the speed tests were
performed by people using one of the three operators we are interested
in. We will filter out all other operators and proceed with speed tests
from these top three operators.

\begin{longtable}[c]{@{}lr@{}}
\toprule\addlinespace
Operator & Number of speedtests
\\\addlinespace
\midrule\endhead
KPN NL & 73496
\\\addlinespace
Vodafone NL & 64982
\\\addlinespace
T-Mobile NL & 59127
\\\addlinespace
Carrier & 3838
\\\addlinespace
Telfort NL & 3329
\\\addlinespace
TURKCELL & 2774
\\\addlinespace
TELE2 & 2470
\\\addlinespace
DiGi & 1834
\\\addlinespace
Hi & 1830
\\\addlinespace
Tele2 NL & 1758
\\\addlinespace
\bottomrule
\addlinespace
\caption{Most frequent operators}
\end{longtable}

The top three operators together are good for 197605 tests conducted all
over the Netherlands in the test period of Q1 2015. We keep only speed
tests from the top three operators.

This leaves 245649 - 48044 = 197605 rows in the data set.

\subsection{Focus on 4G technology}\label{focus-on-4g-technology}

In the raw Ookla Netmetrics data the variable called `connection\_type'
identifies which technology is used, this variable can be transformed
into the network technology used while performing the test.

The variable Connection type defines 4G as connection type 15 for
Android. For iOS connection type 12 is LTE, and for Windows Mobile
connection type 11 is LTE.

Definition of 4G for Android OS from the SQL script(available on GitHub)
:

\begin{Shaded}
\begin{Highlighting}[]
  \KeywordTok{Case}  \KeywordTok{WHEN}  \NormalTok{CONNECTION_TYPE=}\DecValTok{0}         \KeywordTok{THEN} \StringTok{'UNKNOWN'}
    \KeywordTok{WHEN}    \NormalTok{CONNECTION_TYPE }\KeywordTok{in} \NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{)        }\KeywordTok{THEN} \StringTok{'WIFI/CELL'}
    \KeywordTok{WHEN}    \NormalTok{CONNECTION_TYPE }\KeywordTok{in} \NormalTok{(}\DecValTok{3}\NormalTok{,}\DecValTok{4}\NormalTok{)        }\KeywordTok{THEN} \StringTok{'2G'}
    \KeywordTok{WHEN}    \NormalTok{CONNECTION_TYPE=}\DecValTok{15}          \KeywordTok{THEN} \StringTok{'4G'}
    \KeywordTok{WHEN}    \NormalTok{CONNECTION_TYPE }\KeywordTok{between} \DecValTok{5} \KeywordTok{and} \DecValTok{17}    \KeywordTok{THEN} \StringTok{'3G'}
    \KeywordTok{ELSE}    \StringTok{'UNKNOWN'}
  \KeywordTok{END} \KeywordTok{AS} \NormalTok{TECHNOLOGY}
\end{Highlighting}
\end{Shaded}

Below we give an overview of the network technology types available in
the data set.

\begin{longtable}[c]{@{}lrr@{}}
\toprule\addlinespace
& Number of cases & Percentage
\\\addlinespace
\midrule\endhead
2G & 2501 & 1.27
\\\addlinespace
3G & 55002 & 27.83
\\\addlinespace
4G & 139557 & 70.62
\\\addlinespace
UNKNOWN & 69 & 0.03
\\\addlinespace
WIFI/CELL & 476 & 0.24
\\\addlinespace
\bottomrule
\addlinespace
\caption{Technology used in tests}
\end{longtable}

\textbf{In the remainder of this analysis we will focus on 4G
technology.}

Filtering on 4G technology leaves 139557 test cases in the data set.

\subsection{Operating systems}\label{operating-systems}

For the top three operators we can look at the type of operating system
used on these devices:

\begin{longtable}[c]{@{}lrrr@{}}
\toprule\addlinespace
& KPN NL & T-Mobile NL & Vodafone NL
\\\addlinespace
\midrule\endhead
Android & 31528 & 26537 & 28732
\\\addlinespace
iOS & 40066 & 31542 & 34400
\\\addlinespace
Windows & 1902 & 1048 & 1850
\\\addlinespace
\bottomrule
\end{longtable}

Most of the tests were conducted on iOS closely followed by Android OS.
Windows Mobile devices have limited representation in the data set. In
this test we are not interested in testing the difference in performance
per device or operating system.

\subsection{Geographical coverage area for
4G}\label{geographical-coverage-area-for-4g}

For this test to be fair to all three operators, we limit the comparison
of the test to areas in which all three operators (KPN, Vodafone and
T-Mobile) claim to have 4G coverage at the time of the measurements.
While KPN and Vodafone already claim national 4G coverage, T-Mobile is
still in the process of expanding their 4G network. Therefore, T-Mobile
4G coverage area is extended every month. This means that some areas
only got 4G coverage during Q1 2015, the period of the test. All of the
top 20 cities in the Netherlands, which we will analyze per city, had 4G
enabled prior to Q1 2015.

\subsubsection{Coordinates with very high number of
tests}\label{coordinates-with-very-high-number-of-tests}

Are there any locations, or coordinates, that occur very often in the
investigated 4G area? If we join the coordinates latitude and longitude
together and look at the most frequent occurrences we see that there are
indeed some coordinates that are very frequent. How do these exact same
coordinates end up in the data? To understand this we need to explain a
bit more on how the Ookla Speed test application gets the coordinates
from a mobile
device(\href{https://support.speedtest.net/hc/en-us/articles/203845480-Mobile-Test-Server-Selection}{read
more online}). There are several scenario's that can be the case: 1)The
customer has approved the application access to the GPS coordinates of
his/her device. 2)For some reason the app cannot read the GPS
coordinates from the device at the time of the test. This reason can be
of different origins, the user has blocked access or we are in a
building or there are other technical reasons why the exact GPS
coordinates cannot be accessed.

Whenever the exact coordinates are not available, due to measurement
issues or because the customer is not allowing the application to use
the GPS coordinates Ookla uses GEO-IP. GEO-IP is a online service to
estimate the physical location of an ip-internet address (more online
\href{https://www.maxmind.com/en/geoip2-services-and-databases}{from
maxmind} ).

\begin{longtable}[c]{@{}lr@{}}
\toprule\addlinespace
Coordinates & Count
\\\addlinespace
\midrule\endhead
52.3667 , 4.9 & 36692
\\\addlinespace
52.35 , 4.9167 & 2436
\\\addlinespace
51.9167 , 4.5 & 407
\\\addlinespace
52.3666 , 4.9027 & 325
\\\addlinespace
52.0833 , 4.3 & 252
\\\addlinespace
51.8059 , 4.5634 & 179
\\\addlinespace
52.0938 , 5.1191 & 179
\\\addlinespace
52.3881 , 5.2354 & 140
\\\addlinespace
51.8007 , 4.6982 & 139
\\\addlinespace
51.8796 , 4.5059 & 113
\\\addlinespace
52.3025 , 4.6889 & 89
\\\addlinespace
52.0666 , 4.3209 & 65
\\\addlinespace
52.1583 , 4.4931 & 64
\\\addlinespace
52.352 , 4.8875 & 64
\\\addlinespace
51.4408 , 5.4778 & 60
\\\addlinespace
\bottomrule
\end{longtable}

There is a difference between Q4 2014 and Q1 2015. The coordinate
(52.5-5.75) which was the default coordinate for the Netherlands in Q4
2014 and described as `the Center of Kansas for The Netherlands' by
Ookla in the
\href{https://github.com/hugokoopmans/ookla-speedtest-analysis/blob/master/speedtest-analysis-final-1.3.pdf}{Q4/2014
Paper} is no longer present in the data set. Instead, the coordinate
(52.3667, 4.9) is now the most frequent one. We assumed that this is the
new default coordinate for the Netherlands, when the exact location is
unknown. We asked for an explanation from Ookla on this change and
questions on the other frequent and rounded coordinates.

Coordinate (52.3667,4.9 vs 52.5-5.75) : Response from Ookla:
\emph{Results are definitely coming from GEO-IP Coordinates as you know.
2. In a single day here, there is 191 results from the same IP block to
this location. 3. Correct, this is similar to the `Kansas' issue we
discussed last year.}

Coordinate (52.35-4.9167) is in Amsterdam. Question to Ookla: Can we
still assume the measurements are from Amsterdam? Response Ookla:
\emph{Yes, GeoIP is used here. We can assume you are in Amsterdam but
like any other GeoIP location result, the confidence level isn't as high
as it would be if we were able to get location information directly from
the device, meaning if we were able to obtain GPS instead of GEO-IP.}

Coordinate (51.9167-4.5) is in Rotterdam. Again with limited precision,
same response as above from Ookla.

Coordinate (52.0666-4.3209) is in The Hague. All cases are tests with
operator equal to ``T-Mobile NL'' also this location is close to the
T-Mobile office in The Hague. We will exclude these tests as potentially
being from T-Mobile employees.

Also see the
\href{https://en.wikipedia.org/wiki/Decimal_degrees}{precision of the
coordinates} denotes the fact that we are unsure about the exact
location.

\textbf{So what do we do with these suspicious coordinates?} The
``Unknown'' location, which has coordinates (52.3667 , 4.9) and is the
default location from Ookla if the GPS cannot pick up the exact location
during the test, we have 36692 speed tests with this coordinate alone.
We will exclude tests performed at this coordinate from the general
analysis. Nevertheless, we will analyse this set the same way we analyse
individual cities, the result for this set can be found as the last city
labeled ``unknown''.

\textbf{T-Mobile head office} We removed 65 tests from coordinates
``52.0666 , 4.3209'' in The Hague. As they are close to the head-office
of T-Mobile and indeed all tests from this location are done from a
T-Mobile network.

The other locations (``51.9167-4.5'', ``52.35-4.9167'') have been
explained above and there is no knowledge at this point that leads to
exclusion, so these tests remain in the data set.

After removing 65 tests from coordinates ``52.0666 , 4.3209'' in The
Hague and 36692 from the coordinates ``52.0666 , 4.3209'' the data set
contains 139557 - 36757 = 102800 speed tests at this point.

\subsubsection{Mapping test coordiantes to city
boundaries}\label{mapping-test-coordiantes-to-city-boundaries}

To identify the exact 4G coverage area we will use in this analysis, we
use data from CBS. CBS is the Central Bureau of Statistics in the
Netherlands. They provide
\href{http://www.cbs.nl/nl-NL/menu/themas/dossiers/nederland-regionaal/publicaties/geografische-data/archief/2014/2013-wijk-en-buurtkaart-art.htm}{publicly
available} polygon data on cities in the Netherlands. Based on these
geographical city boundaries we map each latitude, longitude coordinate
onto a city.

From T-Mobile we received a list of cities that, at the time of testing,
have 4G coverage. From the data we can see that per city each provider
has sufficient number of speed tests in the data set for the tests to be
representative.

We use city boundaries to not be influenced by exact locations of
network infrastructure. \newpage

Online we can get an up to date overview of network coverage for all
three operators (see \href{http://www.4gdekking.nl/}{here}).

This test is not about coverage but about speed of the 4G network.

T-Mobile has the least 4G coverage of the three operators and per end of
Q1 2015 has actual coverage in the following area:

\includegraphics{speedtest-analysis-Q1-2015_files/figure-latex/area-1.pdf}

In order to do a fair comparison, we focus only on the area presented in
the picture above.

We do a Geo-spacial filter on the latitude and longitude coordinates
provided in the data set and only keep speed tests that are in any of
the above city boundaries. For the area, defined above, the following
number of tests are available in the data set.

\begin{longtable}[c]{@{}lrr@{}}
\toprule\addlinespace
& Number of tests & percentage
\\\addlinespace
\midrule\endhead
KPN NL & 26273 & 31.00
\\\addlinespace
T-Mobile NL & 31985 & 37.74
\\\addlinespace
Vodafone NL & 26492 & 31.26
\\\addlinespace
Sum & 84750 & 100.00
\\\addlinespace
\bottomrule
\addlinespace
\caption{Number of 4G speedtests in the selected coverage area.}
\end{longtable}

Areas where T-Mobile announced 4G coverage in Q1 2015: Buren, Culemborg,
Geldermalsen, Scherpenzeel, Tiel, Neerijnen, Renswoude, Wijk bij
Duurstede, Sint-Michielsgestel, Utrechtse Heuvelrug and Maasdonk, were
added in January; Barneveld, Ede, Veenendaal, Hellevoetsluis, Bernisse,
Korendijk, Cromstrijen, Westvoorne, Strijen, Moerdijk and
Goeree-Overflakkee were added in February; Almelo, Borne, Deventer,
Hengelo, Wierden, Zwolle, Beuningen, Druten, Ermelo, Harderwijk, Hattem,
Lochem, Putten, Voorst, Wageningen, Wijchen, Zutphen, Nunspeet, Rhenen,
West Maas en Waal, Oss, Overbetuwe, Neder-Betuwe and Rijssen-Holten were
added in March.

Naturally, in these cities, almost all of T-Mobile's 4G speedtests occur
after announcing to customers that 4G is activated, so January, February
or March respectively. Even though a very small number of tests were
executed during the extension of the 4G coverage onto these cities, as
4G sites were being added (so before announcing 4G coverage in these
cities; this is possible as for most 4G capable phones, the \newpage 4G
network is selected automatically if available). In the same cities, KPN
and Vodafone speedtests are distributed more evenly over the entire
period of Q1/2015. However, this has no influence on the test results,
as the test results per month do not differ substantially (please see
section 4.6.4).

So we filtered the data set to include only speed tests from the
coverage area, speed tests outside this area are neglected. The data set
now contains 102800 - 18050 = 84750 speed tests.

\subsubsection{Suspicious speeds}\label{suspicious-speeds}

In the data we check for up and download speeds that are technically
impossible. \emph{Download speeds} for 4G are limited to 150Mbps on the
T-mobile technology.

KPN and Vodafone have a technology called LTE advanced which has a
maximum download speed of 225Mbps.

Any speed tests that had a speed recorded above the technical maximum
for that operator was removed from the data set.

So we remove suspicious measurements in which the \textbf{download}
speed exceeded the maximum theoretical speed per individual operator.

For T-Mobile we removed 10 cases, for Vodafone we removed 0 cases and
for KPN we removed 0 cases, because they where above 150(or 225) MBps.

After removing in total 10 of these suspicious measurements, the data
set contains 84740 speed tests at this point.

Let's do the same for \emph{upload speed}.

The maximum theoretical upload speed is for all operators the same:
maximum upload speed of 50Mbps.

So again we remove suspicious measurements in which the \textbf{upload}
speed exceeded the maximum theoretical speed per individual operator.
For T-Mobile we removed 16 cases, for Vodafone we removed 18 cases and
for KPN we removed 25 cases.

After removing in total 59 of these suspicious measurements the data set
contains 84681 speed tests at this point.
\newpage

\subsubsection{Suspicious dates or
times}\label{suspicious-dates-or-times}

We count the number of tests per day for the months January, February
and March of 2015. Again we are looking at any suspicious peaks in the
data.

\begin{center}\includegraphics{speedtest-analysis-Q1-2015_files/figure-latex/timestamps-1} \end{center}

We find no disturbing or unknown peaks on a specific date.

\begin{longtable}[c]{@{}lrrrr@{}}
\toprule\addlinespace
& 01 januari & 02 februari & 03 maart & Sum
\\\addlinespace
\midrule\endhead
KPN NL & 8801 & 8137 & 9310 & 26248
\\\addlinespace
T-Mobile NL & 10877 & 9361 & 11721 & 31959
\\\addlinespace
Vodafone NL & 9511 & 7804 & 9159 & 26474
\\\addlinespace
Sum & 29189 & 25302 & 30190 & 84681
\\\addlinespace
\bottomrule
\addlinespace
\caption{Counts per operator per month}
\end{longtable}

Above a count per month per operator in the 4G coverage area. This is
the data set on which we conduct the remainder of the analysis.

In the tables below we list the averages for download speed, upload
speed and latency per operator per month. Also, here we do not see
fluctuations that are suspiciously high, so the testing frequencies per
month are not a factor.

\begin{longtable}[c]{@{}llr@{}}
\toprule\addlinespace
Operator & Month & Average Downloadspeed(Kbps)
\\\addlinespace
\midrule\endhead
KPN NL & 01 & 22177.8
\\\addlinespace
KPN NL & 02 & 20368.4
\\\addlinespace
KPN NL & 03 & 20422.1
\\\addlinespace
T-Mobile NL & 01 & 36838.3
\\\addlinespace
T-Mobile NL & 02 & 36307.0
\\\addlinespace
T-Mobile NL & 03 & 39148.8
\\\addlinespace
Vodafone NL & 01 & 25808.6
\\\addlinespace
Vodafone NL & 02 & 25731.6
\\\addlinespace
Vodafone NL & 03 & 27323.7
\\\addlinespace
\bottomrule
\addlinespace
\caption{Average download speed(Kbps) per operator per month}
\end{longtable}

Table below shows details for upload speed.

\begin{longtable}[c]{@{}llr@{}}
\toprule\addlinespace
Operator & Month & Average Uploadspeed(Kbps)
\\\addlinespace
\midrule\endhead
KPN NL & februari & 7593.4
\\\addlinespace
KPN NL & januari & 9725.1
\\\addlinespace
KPN NL & maart & 7687.4
\\\addlinespace
T-Mobile NL & februari & 17410.3
\\\addlinespace
T-Mobile NL & januari & 17362.7
\\\addlinespace
T-Mobile NL & maart & 17275.2
\\\addlinespace
Vodafone NL & februari & 13016.3
\\\addlinespace
Vodafone NL & januari & 13415.3
\\\addlinespace
Vodafone NL & maart & 13645.0
\\\addlinespace
\bottomrule
\addlinespace
\caption{Average upload speed(Kbps) per operator per month}
\end{longtable}

Table below shows details for latency.

\begin{longtable}[c]{@{}llr@{}}
\toprule\addlinespace
Operator & Month & Average Latency(ms)
\\\addlinespace
\midrule\endhead
KPN NL & februari & 45.9
\\\addlinespace
KPN NL & januari & 44.1
\\\addlinespace
KPN NL & maart & 46.6
\\\addlinespace
T-Mobile NL & februari & 40.8
\\\addlinespace
T-Mobile NL & januari & 38.6
\\\addlinespace
T-Mobile NL & maart & 41.1
\\\addlinespace
Vodafone NL & februari & 46.0
\\\addlinespace
Vodafone NL & januari & 48.2
\\\addlinespace
Vodafone NL & maart & 48.3
\\\addlinespace
\bottomrule
\addlinespace
\caption{Average latency(ms) per operator per month}
\end{longtable}

\newpage

\section{Step 3: Data analysis}\label{step-3-data-analysis}

So we have pre-processed the data and looked for anomalies in the data.
If found, we have corrected them. Finally we are ready to compare speed
test data between the three major telecom operators in Netherlands in
the above defined coverage area.

We will analyse three different metrics:

\begin{itemize}
\itemsep1pt\parskip0pt\parsep0pt
\item
  Download speed
\item
  Upload speed
\item
  Latency
\end{itemize}

There is no useful way to aggregate these individual metrics into one
overall `speed aggregated score'. Most customers are interested in
download speeds, because it affects the most of their experience
(browsing,streaming,downloading etc). Most network speed comparisons
only focus on download speed. However, since upload speed is also
important for posting video's and photos on social media, and ping times
are important for gaming and fast opening of websites these metrics are
also analyzed.

So how are the different metrics distributed?

\subsection{Histogram distributions}\label{histogram-distributions}

A histogram is a graphical representation of the distribution of data.
It is an estimate of the probability distribution of a continuous
variable (quantitative variable),
\href{https://en.wikipedia.org/wiki/Histogram}{more} about histograms on
Wikipedia.

\subsubsection{Download speed}\label{download-speed}

In the histogram below we see download speed in KBps on the horizontal
axis. The number of test cases are plotted as bars, on the vertical axis
we see the count of the number of speed tests in a specific bin (or
range). The histogram gives a visual representation of the distribution
of the data.

\includegraphics{speedtest-analysis-Q1-2015_files/figure-latex/downloadspeed-1.pdf}

We plot the three histograms, one for each operator, right above each
other so the horizontal axes are aligned. The red lines denotes the mean
(or average) speed of all speed tests for the specific operator. If the
red line is placed to the righthandside in this histogram that means the
average speed for this operator is faster. The red line to the left
means the avarage speed is slower. We can see that the red line of
T-Mobile is farthest to the right so T-Mobile apparently has the highest
average download speed.

\subsubsection{Upload speed}\label{upload-speed}

In the histogram below we see upload speed in KBps on the horizontal
axis. The number of test cases are plotted as bars, on the vertical axis
we see the count of the number of speed tests in a specific bin (or
range). The histogram gives a visual representation of the distribution
of the data.

\includegraphics{speedtest-analysis-Q1-2015_files/figure-latex/uploadspeed-1.pdf}

We plot the three histograms, one for each operator, right above each
other so the horizontal axes are aligned. The red lines denotes the mean
(or average) speed of all speed tests for the specific operator. If the
red line is placed to the righthandside in this histogram that means the
average speed for this operator is faster. The red line to the left
means the avarage speed is slower. We can see that the red line of
T-Mobile is farthest to the right so T-Mobile apparently has the highest
average upload speed as well.

\subsubsection{Latency}\label{latency}

In the histogram below we see log(latency) speed on the horizontal axis.
The log transformation makes the figure more readable. For the reader,
the horizontal axis shows powers of 10. So 2 actually means $10^{2}$ =
100 and 5 actually stands for $10^{5}$ = 10.000 . The number of test
cases are plotted as bars, on the vertical axis we see the count of the
number of speed tests in a specific range. For latency we take the log
so the outlines scale and we can have a look at the shape of the
distribution.

\includegraphics{speedtest-analysis-Q1-2015_files/figure-latex/latency-1.pdf}

For latency smaller is better, so in this plot we are looking at which
operator has the smallest latency. Again we see the red lines per
operator. The x axis are on a log scale to these are factors of ten. The
average latency(red line) for T-Mobile is the most to the left, which
means T-Mobile has the smallest average latency of the three operators.

\subsection{Box-plot}\label{box-plot}

In descriptive statistics, a box plot or box-plot is a convenient way of
graphically depicting groups of numerical data through their quartiles.
Box plots may also have lines extending vertically from the boxes
(whiskers) indicating variability outside the upper and lower quartiles,
hence the terms box-and-whisker plot and box-and-whisker diagram.
Outliers may be plotted as individual points.
\href{https://en.wikipedia.org/wiki/Box_plot}{More} about box-plots on
Wikipedia.

\subsubsection{Download speed}\label{download-speed-1}

We see a box plot for each of the operators on the x axis, the vertical
axis shows the speed test values in Kbps. The daimond shape represents
the mean, the thick line represents the median. the black dots on the
top and bottom represent extreme cases. The data is split up into
quartiles, that means four equally sized proportions. The first and
fourth quarter are represented as a line, the second and third as a box.

\includegraphics{speedtest-analysis-Q1-2015_files/figure-latex/box-down-1.pdf}

Also in the box-plot we see that for T-Mobile the diamond shape(average)
and the thick line representing the median are higher then the same
values for the other operators. So also in this box-plot for download
speed we see that T-Mobile has the highest average and median download
speed.

If we zoom in on percentiles we can look at the fastest 10\%, 5\% and
1\% of speed tests:

\begin{longtable}[c]{@{}lrrr@{}}
\toprule\addlinespace
operator & 10\% & 5\% & 1\%
\\\addlinespace
\midrule\endhead
KPN NL & 39666 & 47011 & 58652
\\\addlinespace
T-Mobile NL & 74088 & 86777 & 108484
\\\addlinespace
Vodafone NL & 50811 & 69454 & 104067
\\\addlinespace
\bottomrule
\addlinespace
\caption{Top percentiles average download speed(Kbps)}
\end{longtable}

From the table we see that T-Mobile scores best in the fastest 10\%,5\%
and 1\% of download speed tests per operator.

\subsubsection{Upload speed}\label{upload-speed-1}

We see a box plot for each of the operators on the x axis, the vertical
axis shows the speed test values in Kbps. The daimond shape represents
the mean, the thick line represents the median. the black dots on the
top and bottom represent extreme cases. The data is split up into
quartiles, that means four equally sized proportions. The first and
fourth quarter are represented as a line, the second and third as a box.

\includegraphics{speedtest-analysis-Q1-2015_files/figure-latex/box-up-1.pdf}

Also in the box-plot we see that for T-Mobile the diamond shape(average)
and the thick line representing the median are higher then the same
values for the other operators. So also in this box-plot for upload
speed we see that T-Mobile has the highest average and median upload
speed.

If we zoom in on percentiles we can look at the fastest 10\%, 5\% and
1\% of speed tests:

\begin{longtable}[c]{@{}lrrr@{}}
\toprule\addlinespace
operator & 10\% & 5\% & 1\%
\\\addlinespace
\midrule\endhead
KPN NL & 17977 & 19167 & 20799
\\\addlinespace
T-Mobile NL & 39883 & 44700 & 47235
\\\addlinespace
Vodafone NL & 24127 & 34539 & 45654
\\\addlinespace
\bottomrule
\addlinespace
\caption{Top percentiles average upload speed(Kbps)}
\end{longtable}

From the table we see that T-Mobile scores best in the fastest 10\%,5\%
and 1\% of upload speed tests per operator.

\subsubsection{Latency}\label{latency-1}

For latency ( or ping) we take the log so the outliers scale and we can
have a look at the shape of the distribution.

We see a box plot for each of the operators on the x axis, the vertical
axis shows the speed test values in Kbps. The daimond shape represents
the mean, the thick line represents the median. the black dots on the
top and bottom represent extreme cases. The data is split up into
quartiles, that means four equally sized proportions. The first and
fourth quarter are represented as a line, the second and third as a box.

\includegraphics{speedtest-analysis-Q1-2015_files/figure-latex/box-latency-1.pdf}

In the box-plot for latancy we see that for T-Mobile the diamond
shape(average) and the thick line representing the median are lower then
the same values for the other operators. Remember, for latancy lower is
better. So in this box-plot for latency we see that T-Mobile has the
lowest latency.

\newpage

\section{Step 4: Test design}\label{step-4-test-design}

What we want to test is if, on average, a customer that uses T-Mobile 4G
Mobile Network gets a higher average speed(in terms of download speed,
upload speed and latency) than a customer using KPN's or Vodafone's 4G
Mobile Network, with all else equal. To do this we have collected
thousands of Ookla NetMetrics Speedtest results taken from the three top
operators (KPN, Vodafone and T-Mobile) which have been filtered as set
out in the above to a final dataset consisting of 84681 data points. Now
we want to compare T-Mobile with the other two operators. So we do two
tests: the first is comparing T-Mobile with KPN and the second is
comparing T-Mobile with Vodafone. In each test we compare all three
metrics: Upload speed, Download speed and latency(or ping). For each
operator we have a sample set available in the data. These sets are so
called samples (from the Dutch population of mobile phone users) from
which we calculate the sample means. Now our statistical test tests if
these sample means are significantly different from one another.

In practice, the Central Limit Theorem assures us that, under a wide
range of assumptions, the distributions of the two sample means being
tested will themselves approach Normal distributions as the sample sizes
get large, regardless (this is where the assumptions come in) of the
distributions of the underlying data. As a consequence, as the sample
size gets larger, the difference of the means becomes normally
distributed, and the requirements necessary for the t-statistic of an
unpaired t-test to have the nominal t distribution become satisfied.

\subsection{Which statistical test do we
need?}\label{which-statistical-test-do-we-need}

What we have here is a set of unpaired, independent, different sample
size, different variance data. A suitable and powerful test for this
kind of data is a
\href{https://en.wikipedia.org/wiki/Welch\%27s_t_test}{Welch t-test}.

In statistics, Welch's t-test (or Welch-Aspin Test) is a two-sample
location test, and is used to check the hypothesis that two populations
have equal means(our NULL hypothesis). Welch's t-test is an adaptation
of Student's t-test, and is intended for use when the two samples have
possibly unequal variances(which is the case here). These tests are
often referred to as ``unpaired'' or ``independent samples'' t-tests, as
they are typically applied when the statistical units underlying the two
samples being compared are non-overlapping(in our case the units are
different people performing the test with different devices on different
networks).

\subsubsection{Significance}\label{significance}

So when is a test significant? And if so at what level? And furthermore
can we qualify such a significant result as good or bad? To start with
the last remark, all qualifications of a statistical result are
subjective. One way of looking at 95\% confidence is that 1 out of 20
trials (in 5\% of the cases) you make a so called Type 1 error, in which
you wrongly reject the null-hypothesis. So in this case, if the p-value
would be 0.05(confidence level 95\%) you would claim that operator x is
faster then operator y while in fact they were not. In applied practice,
confidence intervals are typically stated at the 95\% or 99\% confidence
level (More on
\href{https://en.wikipedia.org/wiki/Statistical_significance}{significance}
).

In our test we will set the confidence level to be 99\%, which is more
strict then 95\%. This means we will reject the Null Hypothesis only if
we are 99 \% confident we do not make a mistake. From the test result we
see that in most cases the calculated p-values are very much smaller
then 1 - 0.99 = 0.01, so changes of making this type of error are even
considerably smaller than the claimed confidence level of 99\%.

\subsubsection{P-value}\label{p-value}

In statistics, the p-value is a function of the observed sample results
(a statistic) that is used for testing a statistical hypothesis. Before
performing the test a threshold value is chosen, called the significance
level of the test, traditionally 5\% or 1\% and denoted as $\alpha$. If
the p-value is equal or smaller than the significance level ($\alpha$),
it suggests that the observed data is inconsistent with the assumption
that the null hypothesis is true, and thus that hypothesis must be
rejected and the alternative hypothesis is accepted as true ( see
\href{https://en.wikipedia.org/wiki/P-value}{wikipedia}).

\subsubsection{Confidence intervals}\label{confidence-intervals}

Confidence intervals consist of a range of values (interval) that act as
good estimates of the unknown population parameter. The level of
confidence of the confidence interval would indicate the probability
that the confidence range captures this true population parameter given
a distribution of samples. This value is represented by a percentage, so
when we say, ``we are 99\% confident that the true value of the
parameter is in our confidence interval'', we express that 99\% of the
observed confidence intervals will hold the true value of the parameter.
A confidence interval does \textbf{not} predict that the true value of
the parameter has a particular probability of being in the confidence
interval given the data actually obtained. (see
\href{https://en.wikipedia.org/wiki/Confidence_interval}{wikipedia}).

\newpage

\section{Step 5: Test results coverage
area}\label{step-5-test-results-coverage-area}

We test T-Mobile against the other two operators so we have two tests.
We put the confidence level to 99 \%. Our null-hypothesis is that the
means are drawn from the same sample, so they are not different.

In this test we use the whole data set, in the next chapter we test each
individual city.

Let see what our test results are:

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 31959 & 37530 & 26248 & 20994 & $<$ 2.22e-16 & Yes & 16535.9 & +/- 415.4 & 78.8 \\ 
  T-Mobile & Vodafone & 31959 & 37530 & 26474 & 26310 & $<$ 2.22e-16 & Yes & 11220 & +/- 489.8 & 42.6 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: download(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 31959 & 17345 & 26248 & 8341 & $<$ 2.22e-16 & Yes & 9003.1 & +/- 226.5 & 107.9 \\ 
  T-Mobile & Vodafone & 31959 & 17345 & 26474 & 13377 & $<$ 2.22e-16 & Yes & 3967.4 & +/- 257.9 & 29.7 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: upload(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(ms) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 31959 & 40 & 26248 & 46 & $<$ 2.22e-16 & Yes & -5.4 & +/- 1.3 & -11.9 \\ 
  T-Mobile & Vodafone & 31959 & 40 & 26474 & 48 & $<$ 2.22e-16 & Yes & -7.5 & +/- 1.3 & -15.8 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: latency(ms)} 
\end{table}

\textbf{Explanation of terms}

\footnotesize
**Sample 1**: Number of speed test samples for operator 1.

\textbf{Sample 2}: Number of speed test samples for operator 2.

\textbf{Mean 1}: Average speed of speed tests for operator 1 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{Mean 2}: Average speed of speed tests for operator 2 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{P-value}: The test statistic, for more explanation see the
paragraph P-Value above

\textbf{Sign.}: Short for Significance. We compare the test statistic
with the predefined confidence level(0.99). `Yes' means the test is
significant, `No' means the test is not significant.``))

\textbf{Diff(in Kbps or ms)}: Difference of the means (DoM) is the
difference of Mean 1 and Mean 2(Mean 1 - Mean 2). For download and
upload speeds(Kbps) big positive number here means operator 1 has a
faster speed then operator 2. A big negative number means that operator
2 has a faster speed then operator 1. For latency(ms) this is the
opposite, because smaller is better.

\textbf{Conf Int}: Confidence interval consist of a range of values
(interval) that act as good estimate of the \emph{true} difference of
the mean. We are 99\% confident that the true value of the difference of
the mean is in our confidence interval.

\textbf{Rel(\%)}: Relative difference in percentage. It is calculated as
the difference of the mean divided by the slower of the two operators
average speed. If the difference is not significant(column Sign is No),
this column will state NA(Not Applicable). The comparison rules are
similar to what is explained in the Diff(in Kbps or ms).

\normalsize
Looking at the tables above we see that all results are significant at
$\alpha$ = 0.01 level(99\% confidence level) and the resulting p-values
are very small. This means we can reject the null-hypothesis with great
confidence. Hence we can state that with 99\% confidence the true
difference in the means lies within the confidence interval provided in
the table.

\newpage

\section{Conclusion}\label{conclusion}

This analysis has been conducted with the utmost care and to the best
knowledge of the analyst (DIKW Consulting). The analysis is opensource
and all code can be downloaded, reviewed and repeated from
\href{https://github.com/hugokoopmans/ookla-speedtest-analysis}{GitHub}.

Overall we can say that based on the speedtest data analysed in the
investigated area the 4G network of T-Mobile outperforms both KPN and
Vodafone on download speed, upload speed and latency.

From the data analysed in the investigated area the average download
speed of the 4G network of T-Mobile outperforms KPN by 16.54 Mbps, which
is 78.8\%. Also, from the data analysed in the investigated area the
average download speed of the 4G network of T-Mobile outperforms
Vodafone by 11.22 Mbps, which is 42.6\%. From table 14 above similar
statements can be derived for upload speed. For deriving these
statements for latency, please see table 15 keeping in mind that smaller
values are better.

For conclusions per individual city we refer to the section below.
Please keep in mind that the significance of a test per city does not
influence the significance of a test over the whole 4G area. The
significance of a test per city only shows if the 4G network speeds
(download speed, upload speed and latency) are also significantly
different on a local level, so for that city treated separately.

\newpage

\section{Analysis and results Top 20 cities per
city}\label{analysis-and-results-top-20-cities-per-city}

From CBS we have the following top 20 cities based on number of
inhabitants(``aantal inwoners'').

\begin{longtable}[c]{@{}llr@{}}
\toprule\addlinespace
gm\_code & gm\_naam & aantal\_inwoners
\\\addlinespace
\midrule\endhead
GM0363 & Amsterdam & 810935
\\\addlinespace
GM0599 & Rotterdam & 618355
\\\addlinespace
GM0518 & 's-Gravenhage & 508940
\\\addlinespace
GM0344 & Utrecht & 328165
\\\addlinespace
GM0772 & Eindhoven & 220920
\\\addlinespace
GM0855 & Tilburg & 210270
\\\addlinespace
GM0014 & Groningen & 198315
\\\addlinespace
GM0034 & Almere & 196010
\\\addlinespace
GM0758 & Breda & 179620
\\\addlinespace
GM0268 & Nijmegen & 168290
\\\addlinespace
GM0153 & Enschede & 158585
\\\addlinespace
GM0200 & Apeldoorn & 157545
\\\addlinespace
GM0392 & Haarlem & 155145
\\\addlinespace
GM0307 & Amersfoort & 150895
\\\addlinespace
GM0202 & Arnhem & 150820
\\\addlinespace
GM0479 & Zaanstad & 150595
\\\addlinespace
GM0394 & Haarlemmermeer & 144060
\\\addlinespace
GM0796 & 's-Hertogenbosch & 143730
\\\addlinespace
GM0637 & Zoetermeer & 123560
\\\addlinespace
GM0935 & Maastricht & 122485
\\\addlinespace
\bottomrule
\end{longtable}

In this test we use the CBS cities in this area as the benchmark area
for the overall comparison.

In more detailed analysis we investigate the top twenty ``Gemeentes''
based on number of inhabitants. based on data available at
\href{http://www.cbs.nl/nl-NL/menu/themas/dossiers/nederland-regionaal/publicaties/geografische-data/archief/2014/2013-wijk-en-buurtkaart-art.htm}{CBS}.

The coverage area of top 20 cities looks like this.

\includegraphics{speedtest-analysis-Q1-2015_files/figure-latex/top20-1.pdf}

From the CBS data we learn that the top 20 cities covers 4855450 out of
16779185 inhabitants. Which is 28.94 \%. in terms of area this is 2412
km\^{}2 of a total of 41545 km\^{}2, which is 5.81\%.

For each city we will do the significance test separately in the next
pages.
\newpage

\subsection{Gemeente Amsterdam}\label{gemeente-amsterdam}

The table shows the speed test analysis for gemeente Amsterdam. For this
test the confidence level is set to 99\%.

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 5113 & 40771 & 2013 & 21541 & $<$ 2.22e-16 & Yes & 19230 & +/- 1232.8 & 89.3 \\ 
  T-Mobile & Vodafone & 5113 & 40771 & 3434 & 33304 & $<$ 2.22e-16 & Yes & 7467.7 & +/- 1449.9 & 22.4 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: download(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 5113 & 18831 & 2013 & 6897 & $<$ 2.22e-16 & Yes & 11934 & +/- 632.8 & 173 \\ 
  T-Mobile & Vodafone & 5113 & 18831 & 3434 & 15482 & $<$ 2.22e-16 & Yes & 3348.7 & +/- 738.8 & 21.6 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: upload(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(ms) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 5113 & 36 & 2013 & 43 & 1.0171e-06 & Yes & -7 & +/- 3.7 & -16.2 \\ 
  T-Mobile & Vodafone & 5113 & 36 & 3434 & 45 & 2.3338e-11 & Yes & -8.4 & +/- 3.2 & -18.8 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: latency(ms)} 
\end{table}

Please note the column {[}Sign.{]} or ``Significant'', if this column
states ``No'' the test is not significant at the 99\% confidence level.
This means there is no significant difference in means observed so the
NULL Hypothesis can not be rejected. In layman's terms: You
\emph{cannot} conclude that one operator has a faster 4G network then
the other on that particular 4G network speed measurement (download
speed, upload speed or latency).

\textbf{Explanation of terms}

\footnotesize
**Sample 1**: Number of speedtest samples for operator 1.

\textbf{Sample 2}: Number of speedtest samples for operator 2.

\textbf{Mean 1}: Average speed of speedtests for operator 1 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{Mean 2}: Average speed of speedtests for operator 2 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{P-value}: The test statistic, for more explanation see the
paragraph P-Value above

\textbf{Sign.}: Short for Significance. We compare the test statistic
with the predefined confidence level(0.99). `Yes' means the test is
significant, `No' means the test is not significant.``))

\textbf{Diff(in Kbps or ms)}: Difference of the means (DoM) is the
difference of Mean 1 and Mean 2(Mean 1 - Mean 2). For download and
upload speeds(Kbps) big positive number here means operator 1 has a
faster speed then operator 2. A big negative number means that operator
2 has a faster speed then operator 1. For latency(ms) this is the
opposite, because smaller is better.

\textbf{Conf Int}: Confidence interval consist of a range of values
(interval) that act as good estimate of the \emph{true} difference of
the mean. We are 99\% confident that the true value of the difference of
the mean is in our confidence interval.

\textbf{Rel(\%)}: Relative difference in percentage. It is calculated as
the difference of the means divided by the slower of the two operators
average speed.

\normalsize

\newpage

\subsection{Gemeente Rotterdam}\label{gemeente-rotterdam}

The table shows the speed test analysis for gemeente Rotterdam. For this
test the confidence level is set to 99\%.

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 2444 & 35716 & 1586 & 21236 & $<$ 2.22e-16 & Yes & 14480.5 & +/- 1484.9 & 68.2 \\ 
  T-Mobile & Vodafone & 2444 & 35716 & 1507 & 34797 & 0.27457 & No & 919.7 & +/- 2169.2 & NA \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: download(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 2444 & 18498 & 1586 & 8959 & $<$ 2.22e-16 & Yes & 9539.2 & +/- 839.3 & 106.5 \\ 
  T-Mobile & Vodafone & 2444 & 18498 & 1507 & 16198 & 7.7252e-08 & Yes & 2299.7 & +/- 1100.6 & 14.2 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: upload(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(ms) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 2444 & 43 & 1586 & 46 & 0.16254 & No & -2.9 & +/- 5.4 & NA \\ 
  T-Mobile & Vodafone & 2444 & 43 & 1507 & 48 & 0.034785 & No & -4.6 & +/- 5.6 & NA \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: latency(ms)} 
\end{table}

Please note the column {[}Sign.{]} or ``Significant'', if this column
states ``No'' the test is not significant at the 99\% confidence level.
This means there is no significant difference in means observed so the
NULL Hypothesis can not be rejected. In layman's terms: You
\emph{cannot} conclude that one operator has a faster 4G network then
the other on that particular 4G network speed measurement (download
speed, upload speed or latency).

\textbf{Explanation of terms}

\footnotesize
**Sample 1**: Number of speedtest samples for operator 1.

\textbf{Sample 2}: Number of speedtest samples for operator 2.

\textbf{Mean 1}: Average speed of speedtests for operator 1 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{Mean 2}: Average speed of speedtests for operator 2 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{P-value}: The test statistic, for more explanation see the
paragraph P-Value above

\textbf{Sign.}: Short for Significance. We compare the test statistic
with the predefined confidence level(0.99). `Yes' means the test is
significant, `No' means the test is not significant.``))

\textbf{Diff(in Kbps or ms)}: Difference of the means (DoM) is the
difference of Mean 1 and Mean 2(Mean 1 - Mean 2). For download and
upload speeds(Kbps) big positive number here means operator 1 has a
faster speed then operator 2. A big negative number means that operator
2 has a faster speed then operator 1. For latency(ms) this is the
opposite, because smaller is better.

\textbf{Conf Int}: Confidence interval consist of a range of values
(interval) that act as good estimate of the \emph{true} difference of
the mean. We are 99\% confident that the true value of the difference of
the mean is in our confidence interval.

\textbf{Rel(\%)}: Relative difference in percentage. It is calculated as
the difference of the means divided by the slower of the two operators
average speed.

\normalsize

\newpage

\subsection{Gemeente 's-Gravenhage}\label{gemeente-s-gravenhage}

The table shows the speed test analysis for gemeente 's-Gravenhage. For
this test the confidence level is set to 99\%.

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 2126 & 34752 & 1533 & 17421 & $<$ 2.22e-16 & Yes & 17331.1 & +/- 1564.8 & 99.5 \\ 
  T-Mobile & Vodafone & 2126 & 34752 & 1297 & 30202 & 1.0229e-07 & Yes & 4550 & +/- 2197.4 & 15.1 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: download(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 2126 & 19470 & 1533 & 8200 & $<$ 2.22e-16 & Yes & 11270 & +/- 903.6 & 137.4 \\ 
  T-Mobile & Vodafone & 2126 & 19470 & 1297 & 13838 & $<$ 2.22e-16 & Yes & 5631.9 & +/- 1155 & 40.7 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: upload(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(ms) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 2126 & 37 & 1533 & 46 & 2.6819e-06 & Yes & -9.6 & +/- 5.2 & -20.7 \\ 
  T-Mobile & Vodafone & 2126 & 37 & 1297 & 49 & 9.9413e-13 & Yes & -12.1 & +/- 4.3 & -24.7 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: latency(ms)} 
\end{table}

Please note the column {[}Sign.{]} or ``Significant'', if this column
states ``No'' the test is not significant at the 99\% confidence level.
This means there is no significant difference in means observed so the
NULL Hypothesis can not be rejected. In layman's terms: You
\emph{cannot} conclude that one operator has a faster 4G network then
the other on that particular 4G network speed measurement (download
speed, upload speed or latency).

\textbf{Explanation of terms}

\footnotesize
**Sample 1**: Number of speedtest samples for operator 1.

\textbf{Sample 2}: Number of speedtest samples for operator 2.

\textbf{Mean 1}: Average speed of speedtests for operator 1 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{Mean 2}: Average speed of speedtests for operator 2 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{P-value}: The test statistic, for more explanation see the
paragraph P-Value above

\textbf{Sign.}: Short for Significance. We compare the test statistic
with the predefined confidence level(0.99). `Yes' means the test is
significant, `No' means the test is not significant.``))

\textbf{Diff(in Kbps or ms)}: Difference of the means (DoM) is the
difference of Mean 1 and Mean 2(Mean 1 - Mean 2). For download and
upload speeds(Kbps) big positive number here means operator 1 has a
faster speed then operator 2. A big negative number means that operator
2 has a faster speed then operator 1. For latency(ms) this is the
opposite, because smaller is better.

\textbf{Conf Int}: Confidence interval consist of a range of values
(interval) that act as good estimate of the \emph{true} difference of
the mean. We are 99\% confident that the true value of the difference of
the mean is in our confidence interval.

\textbf{Rel(\%)}: Relative difference in percentage. It is calculated as
the difference of the means divided by the slower of the two operators
average speed.

\normalsize

\newpage

\subsection{Gemeente Utrecht}\label{gemeente-utrecht}

The table shows the speed test analysis for gemeente Utrecht. For this
test the confidence level is set to 99\%.

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 1198 & 34787 & 824 & 20102 & $<$ 2.22e-16 & Yes & 14685.8 & +/- 2147.4 & 73.1 \\ 
  T-Mobile & Vodafone & 1198 & 34787 & 1142 & 31701 & 0.0024776 & Yes & 3086.1 & +/- 2626.2 & 9.7 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: download(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 1198 & 17666 & 824 & 7099 & $<$ 2.22e-16 & Yes & 10566.9 & +/- 1179.8 & 148.9 \\ 
  T-Mobile & Vodafone & 1198 & 17666 & 1142 & 15644 & 0.0001314 & Yes & 2021.5 & +/- 1360.6 & 12.9 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: upload(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(ms) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 1198 & 39 & 824 & 48 & 1.7272e-06 & Yes & -9.3 & +/- 5 & -19.3 \\ 
  T-Mobile & Vodafone & 1198 & 39 & 1142 & 46 & 0.0001401 & Yes & -6.7 & +/- 4.5 & -14.7 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: latency(ms)} 
\end{table}

Please note the column {[}Sign.{]} or ``Significant'', if this column
states ``No'' the test is not significant at the 99\% confidence level.
This means there is no significant difference in means observed so the
NULL Hypothesis can not be rejected. In layman's terms: You
\emph{cannot} conclude that one operator has a faster 4G network then
the other on that particular 4G network speed measurement (download
speed, upload speed or latency).

\textbf{Explanation of terms}

\footnotesize
**Sample 1**: Number of speedtest samples for operator 1.

\textbf{Sample 2}: Number of speedtest samples for operator 2.

\textbf{Mean 1}: Average speed of speedtests for operator 1 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{Mean 2}: Average speed of speedtests for operator 2 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{P-value}: The test statistic, for more explanation see the
paragraph P-Value above

\textbf{Sign.}: Short for Significance. We compare the test statistic
with the predefined confidence level(0.99). `Yes' means the test is
significant, `No' means the test is not significant.``))

\textbf{Diff(in Kbps or ms)}: Difference of the means (DoM) is the
difference of Mean 1 and Mean 2(Mean 1 - Mean 2). For download and
upload speeds(Kbps) big positive number here means operator 1 has a
faster speed then operator 2. A big negative number means that operator
2 has a faster speed then operator 1. For latency(ms) this is the
opposite, because smaller is better.

\textbf{Conf Int}: Confidence interval consist of a range of values
(interval) that act as good estimate of the \emph{true} difference of
the mean. We are 99\% confident that the true value of the difference of
the mean is in our confidence interval.

\textbf{Rel(\%)}: Relative difference in percentage. It is calculated as
the difference of the means divided by the slower of the two operators
average speed.

\normalsize

\newpage

\subsection{Gemeente Eindhoven}\label{gemeente-eindhoven}

The table shows the speed test analysis for gemeente Eindhoven. For this
test the confidence level is set to 99\%.

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 930 & 35393 & 692 & 22225 & $<$ 2.22e-16 & Yes & 13167.2 & +/- 2308.1 & 59.2 \\ 
  T-Mobile & Vodafone & 930 & 35393 & 824 & 23160 & $<$ 2.22e-16 & Yes & 12233.1 & +/- 2538.9 & 52.8 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: download(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 930 & 17650 & 692 & 9814 & $<$ 2.22e-16 & Yes & 7836 & +/- 1293.7 & 79.8 \\ 
  T-Mobile & Vodafone & 930 & 17650 & 824 & 14050 & 1.1732e-11 & Yes & 3600.1 & +/- 1358.7 & 25.6 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: upload(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(ms) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 930 & 40 & 692 & 45 & 0.021003 & No & -5.6 & +/- 6.2 & NA \\ 
  T-Mobile & Vodafone & 930 & 40 & 824 & 48 & 0.00030102 & Yes & -8.6 & +/- 6.1 & -17.8 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: latency(ms)} 
\end{table}

Please note the column {[}Sign.{]} or ``Significant'', if this column
states ``No'' the test is not significant at the 99\% confidence level.
This means there is no significant difference in means observed so the
NULL Hypothesis can not be rejected. In layman's terms: You
\emph{cannot} conclude that one operator has a faster 4G network then
the other on that particular 4G network speed measurement (download
speed, upload speed or latency).

\textbf{Explanation of terms}

\footnotesize
**Sample 1**: Number of speedtest samples for operator 1.

\textbf{Sample 2}: Number of speedtest samples for operator 2.

\textbf{Mean 1}: Average speed of speedtests for operator 1 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{Mean 2}: Average speed of speedtests for operator 2 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{P-value}: The test statistic, for more explanation see the
paragraph P-Value above

\textbf{Sign.}: Short for Significance. We compare the test statistic
with the predefined confidence level(0.99). `Yes' means the test is
significant, `No' means the test is not significant.``))

\textbf{Diff(in Kbps or ms)}: Difference of the means (DoM) is the
difference of Mean 1 and Mean 2(Mean 1 - Mean 2). For download and
upload speeds(Kbps) big positive number here means operator 1 has a
faster speed then operator 2. A big negative number means that operator
2 has a faster speed then operator 1. For latency(ms) this is the
opposite, because smaller is better.

\textbf{Conf Int}: Confidence interval consist of a range of values
(interval) that act as good estimate of the \emph{true} difference of
the mean. We are 99\% confident that the true value of the difference of
the mean is in our confidence interval.

\textbf{Rel(\%)}: Relative difference in percentage. It is calculated as
the difference of the means divided by the slower of the two operators
average speed.

\normalsize

\newpage

\subsection{Gemeente Tilburg}\label{gemeente-tilburg}

The table shows the speed test analysis for gemeente Tilburg. For this
test the confidence level is set to 99\%.

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 488 & 38980 & 372 & 21647 & $<$ 2.22e-16 & Yes & 17332.5 & +/- 3454.5 & 80.1 \\ 
  T-Mobile & Vodafone & 488 & 38980 & 370 & 23337 & $<$ 2.22e-16 & Yes & 15642.7 & +/- 4104.6 & 67 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: download(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 488 & 17135 & 372 & 10157 & $<$ 2.22e-16 & Yes & 6977.8 & +/- 1768.1 & 68.7 \\ 
  T-Mobile & Vodafone & 488 & 17135 & 370 & 13465 & 2.4283e-06 & Yes & 3670.7 & +/- 1996.6 & 27.3 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: upload(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(ms) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 488 & 39 & 372 & 45 & 0.00065833 & Yes & -6.1 & +/- 4.6 & -13.5 \\ 
  T-Mobile & Vodafone & 488 & 39 & 370 & 48 & 5.752e-08 & Yes & -9.4 & +/- 4.4 & -19.5 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: latency(ms)} 
\end{table}

Please note the column {[}Sign.{]} or ``Significant'', if this column
states ``No'' the test is not significant at the 99\% confidence level.
This means there is no significant difference in means observed so the
NULL Hypothesis can not be rejected. In layman's terms: You
\emph{cannot} conclude that one operator has a faster 4G network then
the other on that particular 4G network speed measurement (download
speed, upload speed or latency).

\textbf{Explanation of terms}

\footnotesize
**Sample 1**: Number of speedtest samples for operator 1.

\textbf{Sample 2}: Number of speedtest samples for operator 2.

\textbf{Mean 1}: Average speed of speedtests for operator 1 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{Mean 2}: Average speed of speedtests for operator 2 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{P-value}: The test statistic, for more explanation see the
paragraph P-Value above

\textbf{Sign.}: Short for Significance. We compare the test statistic
with the predefined confidence level(0.99). `Yes' means the test is
significant, `No' means the test is not significant.``))

\textbf{Diff(in Kbps or ms)}: Difference of the means (DoM) is the
difference of Mean 1 and Mean 2(Mean 1 - Mean 2). For download and
upload speeds(Kbps) big positive number here means operator 1 has a
faster speed then operator 2. A big negative number means that operator
2 has a faster speed then operator 1. For latency(ms) this is the
opposite, because smaller is better.

\textbf{Conf Int}: Confidence interval consist of a range of values
(interval) that act as good estimate of the \emph{true} difference of
the mean. We are 99\% confident that the true value of the difference of
the mean is in our confidence interval.

\textbf{Rel(\%)}: Relative difference in percentage. It is calculated as
the difference of the means divided by the slower of the two operators
average speed.

\normalsize

\newpage

\subsection{Gemeente Groningen}\label{gemeente-groningen}

The table shows the speed test analysis for gemeente Groningen. For this
test the confidence level is set to 99\%.

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 559 & 33354 & 657 & 19479 & $<$ 2.22e-16 & Yes & 13874.8 & +/- 2700.6 & 71.2 \\ 
  T-Mobile & Vodafone & 559 & 33354 & 598 & 20106 & $<$ 2.22e-16 & Yes & 13247.7 & +/- 2677 & 65.9 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: download(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 559 & 15450 & 657 & 9300 & $<$ 2.22e-16 & Yes & 6150.1 & +/- 1537.3 & 66.1 \\ 
  T-Mobile & Vodafone & 559 & 15450 & 598 & 11758 & 1.573e-08 & Yes & 3691.2 & +/- 1670.7 & 31.4 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: upload(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(ms) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 559 & 45 & 657 & 44 & 0.5975 & No & 1.5 & +/- 7.5 & NA \\ 
  T-Mobile & Vodafone & 559 & 45 & 598 & 51 & 0.064212 & No & -5.5 & +/- 7.7 & NA \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: latency(ms)} 
\end{table}

Please note the column {[}Sign.{]} or ``Significant'', if this column
states ``No'' the test is not significant at the 99\% confidence level.
This means there is no significant difference in means observed so the
NULL Hypothesis can not be rejected. In layman's terms: You
\emph{cannot} conclude that one operator has a faster 4G network then
the other on that particular 4G network speed measurement (download
speed, upload speed or latency).

\textbf{Explanation of terms}

\footnotesize
**Sample 1**: Number of speedtest samples for operator 1.

\textbf{Sample 2}: Number of speedtest samples for operator 2.

\textbf{Mean 1}: Average speed of speedtests for operator 1 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{Mean 2}: Average speed of speedtests for operator 2 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{P-value}: The test statistic, for more explanation see the
paragraph P-Value above

\textbf{Sign.}: Short for Significance. We compare the test statistic
with the predefined confidence level(0.99). `Yes' means the test is
significant, `No' means the test is not significant.``))

\textbf{Diff(in Kbps or ms)}: Difference of the means (DoM) is the
difference of Mean 1 and Mean 2(Mean 1 - Mean 2). For download and
upload speeds(Kbps) big positive number here means operator 1 has a
faster speed then operator 2. A big negative number means that operator
2 has a faster speed then operator 1. For latency(ms) this is the
opposite, because smaller is better.

\textbf{Conf Int}: Confidence interval consist of a range of values
(interval) that act as good estimate of the \emph{true} difference of
the mean. We are 99\% confident that the true value of the difference of
the mean is in our confidence interval.

\textbf{Rel(\%)}: Relative difference in percentage. It is calculated as
the difference of the means divided by the slower of the two operators
average speed.

\normalsize

\newpage

\subsection{Gemeente Almere}\label{gemeente-almere}

The table shows the speed test analysis for gemeente Almere. For this
test the confidence level is set to 99\%.

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 533 & 35053 & 429 & 19379 & $<$ 2.22e-16 & Yes & 15674.5 & +/- 3120.6 & 80.9 \\ 
  T-Mobile & Vodafone & 533 & 35053 & 594 & 21300 & $<$ 2.22e-16 & Yes & 13753.1 & +/- 3191.2 & 64.6 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: download(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 533 & 15157 & 429 & 7025 & $<$ 2.22e-16 & Yes & 8131.5 & +/- 1694.8 & 115.7 \\ 
  T-Mobile & Vodafone & 533 & 15157 & 594 & 10398 & 1.4283e-12 & Yes & 4759.2 & +/- 1709.6 & 45.8 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: upload(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(ms) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 533 & 40 & 429 & 45 & 0.11369 & No & -5.1 & +/- 8.4 & NA \\ 
  T-Mobile & Vodafone & 533 & 40 & 594 & 47 & 0.017272 & No & -7.6 & +/- 8.2 & NA \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: latency(ms)} 
\end{table}

Please note the column {[}Sign.{]} or ``Significant'', if this column
states ``No'' the test is not significant at the 99\% confidence level.
This means there is no significant difference in means observed so the
NULL Hypothesis can not be rejected. In layman's terms: You
\emph{cannot} conclude that one operator has a faster 4G network then
the other on that particular 4G network speed measurement (download
speed, upload speed or latency).

\textbf{Explanation of terms}

\footnotesize
**Sample 1**: Number of speedtest samples for operator 1.

\textbf{Sample 2}: Number of speedtest samples for operator 2.

\textbf{Mean 1}: Average speed of speedtests for operator 1 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{Mean 2}: Average speed of speedtests for operator 2 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{P-value}: The test statistic, for more explanation see the
paragraph P-Value above

\textbf{Sign.}: Short for Significance. We compare the test statistic
with the predefined confidence level(0.99). `Yes' means the test is
significant, `No' means the test is not significant.``))

\textbf{Diff(in Kbps or ms)}: Difference of the means (DoM) is the
difference of Mean 1 and Mean 2(Mean 1 - Mean 2). For download and
upload speeds(Kbps) big positive number here means operator 1 has a
faster speed then operator 2. A big negative number means that operator
2 has a faster speed then operator 1. For latency(ms) this is the
opposite, because smaller is better.

\textbf{Conf Int}: Confidence interval consist of a range of values
(interval) that act as good estimate of the \emph{true} difference of
the mean. We are 99\% confident that the true value of the difference of
the mean is in our confidence interval.

\textbf{Rel(\%)}: Relative difference in percentage. It is calculated as
the difference of the means divided by the slower of the two operators
average speed.

\normalsize

\newpage

\subsection{Gemeente Breda}\label{gemeente-breda}

The table shows the speed test analysis for gemeente Breda. For this
test the confidence level is set to 99\%.

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 591 & 40462 & 352 & 19903 & $<$ 2.22e-16 & Yes & 20558.8 & +/- 3220.9 & 103.3 \\ 
  T-Mobile & Vodafone & 591 & 40462 & 351 & 22171 & $<$ 2.22e-16 & Yes & 18290.5 & +/- 3598.5 & 82.5 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: download(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 591 & 19423 & 352 & 8491 & $<$ 2.22e-16 & Yes & 10931.9 & +/- 1838 & 128.7 \\ 
  T-Mobile & Vodafone & 591 & 19423 & 351 & 11270 & $<$ 2.22e-16 & Yes & 8153.8 & +/- 2106.5 & 72.4 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: upload(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(ms) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 591 & 38 & 352 & 47 & 4.2336e-06 & Yes & -9.2 & +/- 5.1 & -19.5 \\ 
  T-Mobile & Vodafone & 591 & 38 & 351 & 48 & 2.2395e-05 & Yes & -9.6 & +/- 5.8 & -20.2 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: latency(ms)} 
\end{table}

Please note the column {[}Sign.{]} or ``Significant'', if this column
states ``No'' the test is not significant at the 99\% confidence level.
This means there is no significant difference in means observed so the
NULL Hypothesis can not be rejected. In layman's terms: You
\emph{cannot} conclude that one operator has a faster 4G network then
the other on that particular 4G network speed measurement (download
speed, upload speed or latency).

\textbf{Explanation of terms}

\footnotesize
**Sample 1**: Number of speedtest samples for operator 1.

\textbf{Sample 2}: Number of speedtest samples for operator 2.

\textbf{Mean 1}: Average speed of speedtests for operator 1 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{Mean 2}: Average speed of speedtests for operator 2 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{P-value}: The test statistic, for more explanation see the
paragraph P-Value above

\textbf{Sign.}: Short for Significance. We compare the test statistic
with the predefined confidence level(0.99). `Yes' means the test is
significant, `No' means the test is not significant.``))

\textbf{Diff(in Kbps or ms)}: Difference of the means (DoM) is the
difference of Mean 1 and Mean 2(Mean 1 - Mean 2). For download and
upload speeds(Kbps) big positive number here means operator 1 has a
faster speed then operator 2. A big negative number means that operator
2 has a faster speed then operator 1. For latency(ms) this is the
opposite, because smaller is better.

\textbf{Conf Int}: Confidence interval consist of a range of values
(interval) that act as good estimate of the \emph{true} difference of
the mean. We are 99\% confident that the true value of the difference of
the mean is in our confidence interval.

\textbf{Rel(\%)}: Relative difference in percentage. It is calculated as
the difference of the means divided by the slower of the two operators
average speed.

\normalsize

\newpage

\subsection{Gemeente Nijmegen}\label{gemeente-nijmegen}

The table shows the speed test analysis for gemeente Nijmegen. For this
test the confidence level is set to 99\%.

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 360 & 31023 & 374 & 22954 & 4.5614e-10 & Yes & 8068.7 & +/- 3294.2 & 35.2 \\ 
  T-Mobile & Vodafone & 360 & 31023 & 346 & 22774 & 8.3285e-11 & Yes & 8248.8 & +/- 3226.2 & 36.2 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: download(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 360 & 15055 & 374 & 8735 & 3.3758e-16 & Yes & 6320.2 & +/- 1939.5 & 72.4 \\ 
  T-Mobile & Vodafone & 360 & 15055 & 346 & 13895 & 0.15949 & No & 1160.8 & +/- 2129.2 & NA \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: upload(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(ms) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 360 & 35 & 374 & 47 & $<$ 2.22e-16 & Yes & -12.4 & +/- 3.3 & -26.4 \\ 
  T-Mobile & Vodafone & 360 & 35 & 346 & 47 & 4.9181e-06 & Yes & -12.4 & +/- 6.9 & -26.4 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: latency(ms)} 
\end{table}

Please note the column {[}Sign.{]} or ``Significant'', if this column
states ``No'' the test is not significant at the 99\% confidence level.
This means there is no significant difference in means observed so the
NULL Hypothesis can not be rejected. In layman's terms: You
\emph{cannot} conclude that one operator has a faster 4G network then
the other on that particular 4G network speed measurement (download
speed, upload speed or latency).

\textbf{Explanation of terms}

\footnotesize
**Sample 1**: Number of speedtest samples for operator 1.

\textbf{Sample 2}: Number of speedtest samples for operator 2.

\textbf{Mean 1}: Average speed of speedtests for operator 1 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{Mean 2}: Average speed of speedtests for operator 2 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{P-value}: The test statistic, for more explanation see the
paragraph P-Value above

\textbf{Sign.}: Short for Significance. We compare the test statistic
with the predefined confidence level(0.99). `Yes' means the test is
significant, `No' means the test is not significant.``))

\textbf{Diff(in Kbps or ms)}: Difference of the means (DoM) is the
difference of Mean 1 and Mean 2(Mean 1 - Mean 2). For download and
upload speeds(Kbps) big positive number here means operator 1 has a
faster speed then operator 2. A big negative number means that operator
2 has a faster speed then operator 1. For latency(ms) this is the
opposite, because smaller is better.

\textbf{Conf Int}: Confidence interval consist of a range of values
(interval) that act as good estimate of the \emph{true} difference of
the mean. We are 99\% confident that the true value of the difference of
the mean is in our confidence interval.

\textbf{Rel(\%)}: Relative difference in percentage. It is calculated as
the difference of the means divided by the slower of the two operators
average speed.

\normalsize

\newpage

\subsection{Gemeente Enschede}\label{gemeente-enschede}

The table shows the speed test analysis for gemeente Enschede. For this
test the confidence level is set to 99\%.

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 418 & 28274 & 306 & 19966 & 1.1046e-13 & Yes & 8308.4 & +/- 2831.6 & 41.6 \\ 
  T-Mobile & Vodafone & 418 & 28274 & 271 & 23011 & 3.7489e-05 & Yes & 5263.6 & +/- 3275.7 & 22.9 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: download(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 418 & 15841 & 306 & 9698 & 2.6727e-14 & Yes & 6143.1 & +/- 2038 & 63.3 \\ 
  T-Mobile & Vodafone & 418 & 15841 & 271 & 12199 & 9.1277e-05 & Yes & 3642.7 & +/- 2390.4 & 29.9 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: upload(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(ms) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 418 & 39 & 306 & 47 & 0.01837 & No & -8.1 & +/- 8.9 & NA \\ 
  T-Mobile & Vodafone & 418 & 39 & 271 & 49 & 0.00079644 & Yes & -10.8 & +/- 8.3 & -21.8 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: latency(ms)} 
\end{table}

Please note the column {[}Sign.{]} or ``Significant'', if this column
states ``No'' the test is not significant at the 99\% confidence level.
This means there is no significant difference in means observed so the
NULL Hypothesis can not be rejected. In layman's terms: You
\emph{cannot} conclude that one operator has a faster 4G network then
the other on that particular 4G network speed measurement (download
speed, upload speed or latency).

\textbf{Explanation of terms}

\footnotesize
**Sample 1**: Number of speedtest samples for operator 1.

\textbf{Sample 2}: Number of speedtest samples for operator 2.

\textbf{Mean 1}: Average speed of speedtests for operator 1 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{Mean 2}: Average speed of speedtests for operator 2 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{P-value}: The test statistic, for more explanation see the
paragraph P-Value above

\textbf{Sign.}: Short for Significance. We compare the test statistic
with the predefined confidence level(0.99). `Yes' means the test is
significant, `No' means the test is not significant.``))

\textbf{Diff(in Kbps or ms)}: Difference of the means (DoM) is the
difference of Mean 1 and Mean 2(Mean 1 - Mean 2). For download and
upload speeds(Kbps) big positive number here means operator 1 has a
faster speed then operator 2. A big negative number means that operator
2 has a faster speed then operator 1. For latency(ms) this is the
opposite, because smaller is better.

\textbf{Conf Int}: Confidence interval consist of a range of values
(interval) that act as good estimate of the \emph{true} difference of
the mean. We are 99\% confident that the true value of the difference of
the mean is in our confidence interval.

\textbf{Rel(\%)}: Relative difference in percentage. It is calculated as
the difference of the means divided by the slower of the two operators
average speed.

\normalsize

\newpage

\subsection{Gemeente Apeldoorn}\label{gemeente-apeldoorn}

The table shows the speed test analysis for gemeente Apeldoorn. For this
test the confidence level is set to 99\%.

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 560 & 34408 & 491 & 21395 & $<$ 2.22e-16 & Yes & 13013.7 & +/- 2841.2 & 60.8 \\ 
  T-Mobile & Vodafone & 560 & 34408 & 377 & 22349 & $<$ 2.22e-16 & Yes & 12059.3 & +/- 3131.3 & 54 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: download(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 560 & 15897 & 491 & 9353 & $<$ 2.22e-16 & Yes & 6544.6 & +/- 1702.4 & 70 \\ 
  T-Mobile & Vodafone & 560 & 15897 & 377 & 11834 & 7.8134e-08 & Yes & 4063.7 & +/- 1937.2 & 34.3 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: upload(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(ms) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 560 & 38 & 491 & 47 & 1.9651e-05 & Yes & -9.3 & +/- 5.6 & -19.6 \\ 
  T-Mobile & Vodafone & 560 & 38 & 377 & 53 & 8.6388e-12 & Yes & -14.4 & +/- 5.4 & -27.4 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: latency(ms)} 
\end{table}

Please note the column {[}Sign.{]} or ``Significant'', if this column
states ``No'' the test is not significant at the 99\% confidence level.
This means there is no significant difference in means observed so the
NULL Hypothesis can not be rejected. In layman's terms: You
\emph{cannot} conclude that one operator has a faster 4G network then
the other on that particular 4G network speed measurement (download
speed, upload speed or latency).

\textbf{Explanation of terms}

\footnotesize
**Sample 1**: Number of speedtest samples for operator 1.

\textbf{Sample 2}: Number of speedtest samples for operator 2.

\textbf{Mean 1}: Average speed of speedtests for operator 1 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{Mean 2}: Average speed of speedtests for operator 2 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{P-value}: The test statistic, for more explanation see the
paragraph P-Value above

\textbf{Sign.}: Short for Significance. We compare the test statistic
with the predefined confidence level(0.99). `Yes' means the test is
significant, `No' means the test is not significant.``))

\textbf{Diff(in Kbps or ms)}: Difference of the means (DoM) is the
difference of Mean 1 and Mean 2(Mean 1 - Mean 2). For download and
upload speeds(Kbps) big positive number here means operator 1 has a
faster speed then operator 2. A big negative number means that operator
2 has a faster speed then operator 1. For latency(ms) this is the
opposite, because smaller is better.

\textbf{Conf Int}: Confidence interval consist of a range of values
(interval) that act as good estimate of the \emph{true} difference of
the mean. We are 99\% confident that the true value of the difference of
the mean is in our confidence interval.

\textbf{Rel(\%)}: Relative difference in percentage. It is calculated as
the difference of the means divided by the slower of the two operators
average speed.

\normalsize

\newpage

\subsection{Gemeente Haarlem}\label{gemeente-haarlem}

The table shows the speed test analysis for gemeente Haarlem. For this
test the confidence level is set to 99\%.

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 538 & 46356 & 356 & 21371 & $<$ 2.22e-16 & Yes & 24985.5 & +/- 3711.4 & 116.9 \\ 
  T-Mobile & Vodafone & 538 & 46356 & 428 & 16952 & $<$ 2.22e-16 & Yes & 29403.9 & +/- 3675.9 & 173.5 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: download(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 538 & 21639 & 356 & 6674 & $<$ 2.22e-16 & Yes & 14965.7 & +/- 1845.8 & 224.2 \\ 
  T-Mobile & Vodafone & 538 & 21639 & 428 & 9439 & $<$ 2.22e-16 & Yes & 12200 & +/- 1954.6 & 129.2 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: upload(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(ms) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 538 & 40 & 356 & 45 & 0.026706 & No & -5.6 & +/- 6.5 & NA \\ 
  T-Mobile & Vodafone & 538 & 40 & 428 & 43 & 0.13256 & No & -3.7 & +/- 6.3 & NA \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: latency(ms)} 
\end{table}

Please note the column {[}Sign.{]} or ``Significant'', if this column
states ``No'' the test is not significant at the 99\% confidence level.
This means there is no significant difference in means observed so the
NULL Hypothesis can not be rejected. In layman's terms: You
\emph{cannot} conclude that one operator has a faster 4G network then
the other on that particular 4G network speed measurement (download
speed, upload speed or latency).

\textbf{Explanation of terms}

\footnotesize
**Sample 1**: Number of speedtest samples for operator 1.

\textbf{Sample 2}: Number of speedtest samples for operator 2.

\textbf{Mean 1}: Average speed of speedtests for operator 1 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{Mean 2}: Average speed of speedtests for operator 2 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{P-value}: The test statistic, for more explanation see the
paragraph P-Value above

\textbf{Sign.}: Short for Significance. We compare the test statistic
with the predefined confidence level(0.99). `Yes' means the test is
significant, `No' means the test is not significant.``))

\textbf{Diff(in Kbps or ms)}: Difference of the means (DoM) is the
difference of Mean 1 and Mean 2(Mean 1 - Mean 2). For download and
upload speeds(Kbps) big positive number here means operator 1 has a
faster speed then operator 2. A big negative number means that operator
2 has a faster speed then operator 1. For latency(ms) this is the
opposite, because smaller is better.

\textbf{Conf Int}: Confidence interval consist of a range of values
(interval) that act as good estimate of the \emph{true} difference of
the mean. We are 99\% confident that the true value of the difference of
the mean is in our confidence interval.

\textbf{Rel(\%)}: Relative difference in percentage. It is calculated as
the difference of the means divided by the slower of the two operators
average speed.

\normalsize

\newpage

\subsection{Gemeente Amersfoort}\label{gemeente-amersfoort}

The table shows the speed test analysis for gemeente Amersfoort. For
this test the confidence level is set to 99\%.

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 335 & 30536 & 393 & 20355 & 7.558e-14 & Yes & 10181.3 & +/- 3421.5 & 50 \\ 
  T-Mobile & Vodafone & 335 & 30536 & 398 & 22704 & 1.9166e-08 & Yes & 7832.4 & +/- 3550.1 & 34.5 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: download(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 335 & 15276 & 393 & 6495 & $<$ 2.22e-16 & Yes & 8780.6 & +/- 1988.2 & 135.2 \\ 
  T-Mobile & Vodafone & 335 & 15276 & 398 & 11296 & 1.5549e-06 & Yes & 3980.3 & +/- 2118.5 & 35.2 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: upload(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(ms) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 335 & 39 & 393 & 50 & 0.0010665 & Yes & -11 & +/- 8.6 & -22.1 \\ 
  T-Mobile & Vodafone & 335 & 39 & 398 & 46 & 1.3355e-11 & Yes & -6.9 & +/- 2.6 & -15.1 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: latency(ms)} 
\end{table}

Please note the column {[}Sign.{]} or ``Significant'', if this column
states ``No'' the test is not significant at the 99\% confidence level.
This means there is no significant difference in means observed so the
NULL Hypothesis can not be rejected. In layman's terms: You
\emph{cannot} conclude that one operator has a faster 4G network then
the other on that particular 4G network speed measurement (download
speed, upload speed or latency).

\textbf{Explanation of terms}

\footnotesize
**Sample 1**: Number of speedtest samples for operator 1.

\textbf{Sample 2}: Number of speedtest samples for operator 2.

\textbf{Mean 1}: Average speed of speedtests for operator 1 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{Mean 2}: Average speed of speedtests for operator 2 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{P-value}: The test statistic, for more explanation see the
paragraph P-Value above

\textbf{Sign.}: Short for Significance. We compare the test statistic
with the predefined confidence level(0.99). `Yes' means the test is
significant, `No' means the test is not significant.``))

\textbf{Diff(in Kbps or ms)}: Difference of the means (DoM) is the
difference of Mean 1 and Mean 2(Mean 1 - Mean 2). For download and
upload speeds(Kbps) big positive number here means operator 1 has a
faster speed then operator 2. A big negative number means that operator
2 has a faster speed then operator 1. For latency(ms) this is the
opposite, because smaller is better.

\textbf{Conf Int}: Confidence interval consist of a range of values
(interval) that act as good estimate of the \emph{true} difference of
the mean. We are 99\% confident that the true value of the difference of
the mean is in our confidence interval.

\textbf{Rel(\%)}: Relative difference in percentage. It is calculated as
the difference of the means divided by the slower of the two operators
average speed.

\normalsize

\newpage

\subsection{Gemeente Arnhem}\label{gemeente-arnhem}

The table shows the speed test analysis for gemeente Arnhem. For this
test the confidence level is set to 99\%.

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 599 & 30499 & 550 & 21320 & $<$ 2.22e-16 & Yes & 9178.5 & +/- 2513.2 & 43.1 \\ 
  T-Mobile & Vodafone & 599 & 30499 & 459 & 22831 & 4.7645e-08 & Yes & 7667.8 & +/- 3593.9 & 33.6 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: download(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 599 & 15619 & 550 & 10682 & 9.4842e-16 & Yes & 4936.9 & +/- 1557.6 & 46.2 \\ 
  T-Mobile & Vodafone & 599 & 15619 & 459 & 12291 & 2.1371e-06 & Yes & 3328.1 & +/- 1801.8 & 27.1 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: upload(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(ms) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 599 & 34 & 550 & 42 & $<$ 2.22e-16 & Yes & -7.8 & +/- 1.7 & -18.5 \\ 
  T-Mobile & Vodafone & 599 & 34 & 459 & 44 & $<$ 2.22e-16 & Yes & -10 & +/- 2.6 & -22.5 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: latency(ms)} 
\end{table}

Please note the column {[}Sign.{]} or ``Significant'', if this column
states ``No'' the test is not significant at the 99\% confidence level.
This means there is no significant difference in means observed so the
NULL Hypothesis can not be rejected. In layman's terms: You
\emph{cannot} conclude that one operator has a faster 4G network then
the other on that particular 4G network speed measurement (download
speed, upload speed or latency).

\textbf{Explanation of terms}

\footnotesize
**Sample 1**: Number of speedtest samples for operator 1.

\textbf{Sample 2}: Number of speedtest samples for operator 2.

\textbf{Mean 1}: Average speed of speedtests for operator 1 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{Mean 2}: Average speed of speedtests for operator 2 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{P-value}: The test statistic, for more explanation see the
paragraph P-Value above

\textbf{Sign.}: Short for Significance. We compare the test statistic
with the predefined confidence level(0.99). `Yes' means the test is
significant, `No' means the test is not significant.``))

\textbf{Diff(in Kbps or ms)}: Difference of the means (DoM) is the
difference of Mean 1 and Mean 2(Mean 1 - Mean 2). For download and
upload speeds(Kbps) big positive number here means operator 1 has a
faster speed then operator 2. A big negative number means that operator
2 has a faster speed then operator 1. For latency(ms) this is the
opposite, because smaller is better.

\textbf{Conf Int}: Confidence interval consist of a range of values
(interval) that act as good estimate of the \emph{true} difference of
the mean. We are 99\% confident that the true value of the difference of
the mean is in our confidence interval.

\textbf{Rel(\%)}: Relative difference in percentage. It is calculated as
the difference of the means divided by the slower of the two operators
average speed.

\normalsize

\newpage

\subsection{Gemeente Zaanstad}\label{gemeente-zaanstad}

The table shows the speed test analysis for gemeente Zaanstad. For this
test the confidence level is set to 99\%.

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 321 & 35373 & 243 & 20308 & $<$ 2.22e-16 & Yes & 15065 & +/- 4120.6 & 74.2 \\ 
  T-Mobile & Vodafone & 321 & 35373 & 295 & 20660 & $<$ 2.22e-16 & Yes & 14712.6 & +/- 3945.7 & 71.2 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: download(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 321 & 17130 & 243 & 7039 & $<$ 2.22e-16 & Yes & 10091.3 & +/- 2218.7 & 143.4 \\ 
  T-Mobile & Vodafone & 321 & 17130 & 295 & 14717 & 0.013395 & No & 2412.6 & +/- 2513.3 & NA \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: upload(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(ms) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 321 & 40 & 243 & 43 & 0.47717 & No & -3.6 & +/- 13 & NA \\ 
  T-Mobile & Vodafone & 321 & 40 & 295 & 46 & 0.2202 & No & -6.8 & +/- 14.4 & NA \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: latency(ms)} 
\end{table}

Please note the column {[}Sign.{]} or ``Significant'', if this column
states ``No'' the test is not significant at the 99\% confidence level.
This means there is no significant difference in means observed so the
NULL Hypothesis can not be rejected. In layman's terms: You
\emph{cannot} conclude that one operator has a faster 4G network then
the other on that particular 4G network speed measurement (download
speed, upload speed or latency).

\textbf{Explanation of terms}

\footnotesize
**Sample 1**: Number of speedtest samples for operator 1.

\textbf{Sample 2}: Number of speedtest samples for operator 2.

\textbf{Mean 1}: Average speed of speedtests for operator 1 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{Mean 2}: Average speed of speedtests for operator 2 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{P-value}: The test statistic, for more explanation see the
paragraph P-Value above

\textbf{Sign.}: Short for Significance. We compare the test statistic
with the predefined confidence level(0.99). `Yes' means the test is
significant, `No' means the test is not significant.``))

\textbf{Diff(in Kbps or ms)}: Difference of the means (DoM) is the
difference of Mean 1 and Mean 2(Mean 1 - Mean 2). For download and
upload speeds(Kbps) big positive number here means operator 1 has a
faster speed then operator 2. A big negative number means that operator
2 has a faster speed then operator 1. For latency(ms) this is the
opposite, because smaller is better.

\textbf{Conf Int}: Confidence interval consist of a range of values
(interval) that act as good estimate of the \emph{true} difference of
the mean. We are 99\% confident that the true value of the difference of
the mean is in our confidence interval.

\textbf{Rel(\%)}: Relative difference in percentage. It is calculated as
the difference of the means divided by the slower of the two operators
average speed.

\normalsize

\newpage

\subsection{Gemeente Haarlemmermeer}\label{gemeente-haarlemmermeer}

The table shows the speed test analysis for gemeente Haarlemmermeer. For
this test the confidence level is set to 99\%.

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 657 & 38864 & 556 & 19294 & $<$ 2.22e-16 & Yes & 19569.7 & +/- 2730.1 & 101.4 \\ 
  T-Mobile & Vodafone & 657 & 38864 & 646 & 27694 & $<$ 2.22e-16 & Yes & 11170 & +/- 3199.6 & 40.3 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: download(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 657 & 17793 & 556 & 5907 & $<$ 2.22e-16 & Yes & 11886.1 & +/- 1576 & 201.2 \\ 
  T-Mobile & Vodafone & 657 & 17793 & 646 & 13652 & 3.5088e-10 & Yes & 4141 & +/- 1687.4 & 30.3 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: upload(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(ms) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 657 & 41 & 556 & 43 & 0.61922 & No & -1.6 & +/- 8.3 & NA \\ 
  T-Mobile & Vodafone & 657 & 41 & 646 & 51 & 0.0073601 & Yes & -9.9 & +/- 9.5 & -19.5 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: latency(ms)} 
\end{table}

Please note the column {[}Sign.{]} or ``Significant'', if this column
states ``No'' the test is not significant at the 99\% confidence level.
This means there is no significant difference in means observed so the
NULL Hypothesis can not be rejected. In layman's terms: You
\emph{cannot} conclude that one operator has a faster 4G network then
the other on that particular 4G network speed measurement (download
speed, upload speed or latency).

\textbf{Explanation of terms}

\footnotesize
**Sample 1**: Number of speedtest samples for operator 1.

\textbf{Sample 2}: Number of speedtest samples for operator 2.

\textbf{Mean 1}: Average speed of speedtests for operator 1 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{Mean 2}: Average speed of speedtests for operator 2 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{P-value}: The test statistic, for more explanation see the
paragraph P-Value above

\textbf{Sign.}: Short for Significance. We compare the test statistic
with the predefined confidence level(0.99). `Yes' means the test is
significant, `No' means the test is not significant.``))

\textbf{Diff(in Kbps or ms)}: Difference of the means (DoM) is the
difference of Mean 1 and Mean 2(Mean 1 - Mean 2). For download and
upload speeds(Kbps) big positive number here means operator 1 has a
faster speed then operator 2. A big negative number means that operator
2 has a faster speed then operator 1. For latency(ms) this is the
opposite, because smaller is better.

\textbf{Conf Int}: Confidence interval consist of a range of values
(interval) that act as good estimate of the \emph{true} difference of
the mean. We are 99\% confident that the true value of the difference of
the mean is in our confidence interval.

\textbf{Rel(\%)}: Relative difference in percentage. It is calculated as
the difference of the means divided by the slower of the two operators
average speed.

\normalsize

\newpage

\subsection{Gemeente 's-Hertogenbosch}\label{gemeente-s-hertogenbosch}

The table shows the speed test analysis for gemeente 's-Hertogenbosch.
For this test the confidence level is set to 99\%.

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 351 & 37852 & 428 & 24363 & 1.154e-15 & Yes & 13489.1 & +/- 4213.3 & 55.4 \\ 
  T-Mobile & Vodafone & 351 & 37852 & 398 & 26991 & 1.3152e-09 & Yes & 10861.5 & +/- 4555.7 & 40.2 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: download(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 351 & 17205 & 428 & 11461 & 2.504e-12 & Yes & 5743.6 & +/- 2065.5 & 50.1 \\ 
  T-Mobile & Vodafone & 351 & 17205 & 398 & 11885 & 7.8377e-10 & Yes & 5320.5 & +/- 2198.6 & 44.8 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: upload(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(ms) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 351 & 38 & 428 & 47 & 1.4176e-12 & Yes & -8.8 & +/- 3.2 & -18.7 \\ 
  T-Mobile & Vodafone & 351 & 38 & 398 & 48 & $<$ 2.22e-16 & Yes & -9.5 & +/- 2.8 & -20 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: latency(ms)} 
\end{table}

Please note the column {[}Sign.{]} or ``Significant'', if this column
states ``No'' the test is not significant at the 99\% confidence level.
This means there is no significant difference in means observed so the
NULL Hypothesis can not be rejected. In layman's terms: You
\emph{cannot} conclude that one operator has a faster 4G network then
the other on that particular 4G network speed measurement (download
speed, upload speed or latency).

\textbf{Explanation of terms}

\footnotesize
**Sample 1**: Number of speedtest samples for operator 1.

\textbf{Sample 2}: Number of speedtest samples for operator 2.

\textbf{Mean 1}: Average speed of speedtests for operator 1 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{Mean 2}: Average speed of speedtests for operator 2 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{P-value}: The test statistic, for more explanation see the
paragraph P-Value above

\textbf{Sign.}: Short for Significance. We compare the test statistic
with the predefined confidence level(0.99). `Yes' means the test is
significant, `No' means the test is not significant.``))

\textbf{Diff(in Kbps or ms)}: Difference of the means (DoM) is the
difference of Mean 1 and Mean 2(Mean 1 - Mean 2). For download and
upload speeds(Kbps) big positive number here means operator 1 has a
faster speed then operator 2. A big negative number means that operator
2 has a faster speed then operator 1. For latency(ms) this is the
opposite, because smaller is better.

\textbf{Conf Int}: Confidence interval consist of a range of values
(interval) that act as good estimate of the \emph{true} difference of
the mean. We are 99\% confident that the true value of the difference of
the mean is in our confidence interval.

\textbf{Rel(\%)}: Relative difference in percentage. It is calculated as
the difference of the means divided by the slower of the two operators
average speed.

\normalsize

\newpage

\subsection{Gemeente Zoetermeer}\label{gemeente-zoetermeer}

The table shows the speed test analysis for gemeente Zoetermeer. For
this test the confidence level is set to 99\%.

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 369 & 41549 & 279 & 18162 & $<$ 2.22e-16 & Yes & 23387 & +/- 3908.4 & 128.8 \\ 
  T-Mobile & Vodafone & 369 & 41549 & 254 & 23845 & $<$ 2.22e-16 & Yes & 17703.6 & +/- 5163.5 & 74.2 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: download(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 369 & 18936 & 279 & 7670 & $<$ 2.22e-16 & Yes & 11266.2 & +/- 2207.6 & 146.9 \\ 
  T-Mobile & Vodafone & 369 & 18936 & 254 & 14951 & 0.00048064 & Yes & 3985.4 & +/- 2933.2 & 26.7 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: upload(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(ms) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 369 & 36 & 279 & 42 & 0.077805 & No & -6.1 & +/- 8.9 & NA \\ 
  T-Mobile & Vodafone & 369 & 36 & 254 & 52 & 8.1805e-05 & Yes & -16.2 & +/- 10.5 & -30.9 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: latency(ms)} 
\end{table}

Please note the column {[}Sign.{]} or ``Significant'', if this column
states ``No'' the test is not significant at the 99\% confidence level.
This means there is no significant difference in means observed so the
NULL Hypothesis can not be rejected. In layman's terms: You
\emph{cannot} conclude that one operator has a faster 4G network then
the other on that particular 4G network speed measurement (download
speed, upload speed or latency).

\textbf{Explanation of terms}

\footnotesize
**Sample 1**: Number of speedtest samples for operator 1.

\textbf{Sample 2}: Number of speedtest samples for operator 2.

\textbf{Mean 1}: Average speed of speedtests for operator 1 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{Mean 2}: Average speed of speedtests for operator 2 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{P-value}: The test statistic, for more explanation see the
paragraph P-Value above

\textbf{Sign.}: Short for Significance. We compare the test statistic
with the predefined confidence level(0.99). `Yes' means the test is
significant, `No' means the test is not significant.``))

\textbf{Diff(in Kbps or ms)}: Difference of the means (DoM) is the
difference of Mean 1 and Mean 2(Mean 1 - Mean 2). For download and
upload speeds(Kbps) big positive number here means operator 1 has a
faster speed then operator 2. A big negative number means that operator
2 has a faster speed then operator 1. For latency(ms) this is the
opposite, because smaller is better.

\textbf{Conf Int}: Confidence interval consist of a range of values
(interval) that act as good estimate of the \emph{true} difference of
the mean. We are 99\% confident that the true value of the difference of
the mean is in our confidence interval.

\textbf{Rel(\%)}: Relative difference in percentage. It is calculated as
the difference of the means divided by the slower of the two operators
average speed.

\normalsize

\newpage

\subsection{Gemeente Maastricht}\label{gemeente-maastricht}

The table shows the speed test analysis for gemeente Maastricht. For
this test the confidence level is set to 99\%.

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 399 & 31197 & 143 & 22721 & 4.3237e-08 & Yes & 8475.6 & +/- 3926.1 & 37.3 \\ 
  T-Mobile & Vodafone & 399 & 31197 & 913 & 34553 & 0.017463 & No & -3356.3 & +/- 3638.1 & NA \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: download(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 399 & 13247 & 143 & 10785 & 0.0017979 & Yes & 2461.9 & +/- 2027.5 & 22.8 \\ 
  T-Mobile & Vodafone & 399 & 13247 & 913 & 15895 & 3.2162e-05 & Yes & -2648.2 & +/- 1634.4 & -20 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: upload(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(ms) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 399 & 63 & 143 & 70 & 0.033528 & No & -7.6 & +/- 9.2 & NA \\ 
  T-Mobile & Vodafone & 399 & 63 & 913 & 60 & 0.39254 & No & 3.2 & +/- 9.6 & NA \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: latency(ms)} 
\end{table}

Please note the column {[}Sign.{]} or ``Significant'', if this column
states ``No'' the test is not significant at the 99\% confidence level.
This means there is no significant difference in means observed so the
NULL Hypothesis can not be rejected. In layman's terms: You
\emph{cannot} conclude that one operator has a faster 4G network then
the other on that particular 4G network speed measurement (download
speed, upload speed or latency).

\textbf{Explanation of terms}

\footnotesize
**Sample 1**: Number of speedtest samples for operator 1.

\textbf{Sample 2}: Number of speedtest samples for operator 2.

\textbf{Mean 1}: Average speed of speedtests for operator 1 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{Mean 2}: Average speed of speedtests for operator 2 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{P-value}: The test statistic, for more explanation see the
paragraph P-Value above

\textbf{Sign.}: Short for Significance. We compare the test statistic
with the predefined confidence level(0.99). `Yes' means the test is
significant, `No' means the test is not significant.``))

\textbf{Diff(in Kbps or ms)}: Difference of the means (DoM) is the
difference of Mean 1 and Mean 2(Mean 1 - Mean 2). For download and
upload speeds(Kbps) big positive number here means operator 1 has a
faster speed then operator 2. A big negative number means that operator
2 has a faster speed then operator 1. For latency(ms) this is the
opposite, because smaller is better.

\textbf{Conf Int}: Confidence interval consist of a range of values
(interval) that act as good estimate of the \emph{true} difference of
the mean. We are 99\% confident that the true value of the difference of
the mean is in our confidence interval.

\textbf{Rel(\%)}: Relative difference in percentage. It is calculated as
the difference of the means divided by the slower of the two operators
average speed.

\normalsize

\newpage

\subsection{Gemeente Unkown Location}\label{gemeente-unkown-location}

The table shows the speed test analysis for gemeente Unkown Location.
For this test the confidence level is set to 99\%.

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 7734 & 40284 & 15008 & 22403 & $<$ 2.22e-16 & Yes & 17880.6 & +/- 799.4 & 79.8 \\ 
  T-Mobile & Vodafone & 7734 & 40284 & 13950 & 25164 & $<$ 2.22e-16 & Yes & 15119.6 & +/- 861.6 & 60.1 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: download(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(Kbps) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 7734 & 17178 & 15008 & 8288 & $<$ 2.22e-16 & Yes & 8890.7 & +/- 429.9 & 107.3 \\ 
  T-Mobile & Vodafone & 7734 & 17178 & 13950 & 13090 & $<$ 2.22e-16 & Yes & 4088.5 & +/- 457.6 & 31.2 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: upload(kbps)} 
\end{table}

\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{lllllllllll}
  \hline
Operator1 & Operator2 & Sample1 & Mean1 & Sample2 & Mean2 & P-value & Sign. & Diff(ms) & Conf Int & Rel(\%) \\ 
  \hline
T-Mobile & KPN & 7734 & 38 & 15008 & 43 & 8.7996e-14 & Yes & -5.7 & +/- 2 & -13.2 \\ 
  T-Mobile & Vodafone & 7734 & 38 & 13950 & 47 & $<$ 2.22e-16 & Yes & -9.6 & +/- 2 & -20.3 \\ 
   \hline
\end{tabular}
}
\caption{Comparison of means for metric: latency(ms)} 
\end{table}

Please note the column {[}Sign.{]} or ``Significant'', if this column
states ``No'' the test is not significant at the 99\% confidence level.
This means there is no significant difference in means observed so the
NULL Hypothesis can not be rejected. In layman's terms: You
\emph{cannot} conclude that one operator has a faster 4G network then
the other on that particular 4G network speed measurement (download
speed, upload speed or latency).

\textbf{Explanation of terms}

\footnotesize
**Sample 1**: Number of speedtest samples for operator 1.

\textbf{Sample 2}: Number of speedtest samples for operator 2.

\textbf{Mean 1}: Average speed of speedtests for operator 1 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{Mean 2}: Average speed of speedtests for operator 2 in KBps. A
high number here means that this operator has a fast download(or upload)
speed. For the latency a high number means you have to wait longer to
contact webpages or servers.

\textbf{P-value}: The test statistic, for more explanation see the
paragraph P-Value above

\textbf{Sign.}: Short for Significance. We compare the test statistic
with the predefined confidence level(0.99). `Yes' means the test is
significant, `No' means the test is not significant.``))

\textbf{Diff(in Kbps or ms)}: Difference of the means (DoM) is the
difference of Mean 1 and Mean 2(Mean 1 - Mean 2). For download and
upload speeds(Kbps) big positive number here means operator 1 has a
faster speed then operator 2. A big negative number means that operator
2 has a faster speed then operator 1. For latency(ms) this is the
opposite, because smaller is better.

\textbf{Conf Int}: Confidence interval consist of a range of values
(interval) that act as good estimate of the \emph{true} difference of
the mean. We are 99\% confident that the true value of the difference of
the mean is in our confidence interval.

\textbf{Rel(\%)}: Relative difference in percentage. It is calculated as
the difference of the means divided by the slower of the two operators
average speed.

\normalsize

\end{document}
