-- data loaded from tmp
COPY PI_OOKLA_IPHONE_DATA
FROM '/tmp/tm/iphone.psv'
WITH DELIMITER '|'
CSV HEADER;

-- trema in data
-- type windows1258
COPY PI_OOKLA_ANDROID_DATA
FROM '/tmp/tm/android.psv'
WITH DELIMITER '|'
--ENCODING 'WIN1258'
CSV HEADER;

COPY PI_OOKLA_WP_DATA
FROM '/tmp/tm/wp.psv'
WITH DELIMITER '|'
CSV HEADER;

COPY tm4gcoverage
FROM '/tmp/TMNL_GEMEENTE_4G.csv'
WITH DELIMITER ','
ENCODING 'WIN1258'
CSV HEADER;