INSERT INTO OOKLA_ALL_DATA
	(OS,TEST_ID,DEVICE_ID,TEST_DATE,CLIENT_IP_ADDRESS,DOWNLOAD_KBPS,UPLOAD_KBPS
	,LATENCY,SERVER_NAME,SERVER_COUNTRY,SERVER_COUNTRY_CODE,SERVER_LATITUDE,SERVER_LONGITUDE
	,SERVER_SPONSOR_NAME,CLIENT_COUNTRY,CLIENT_COUNTRY_CODE,CLIENT_REGION_NAME,CLIENT_REGION_CODE
	,CLIENT_CITY,CLIENT_LATITUDE,CLIENT_LONGITUDE,MILES_BETWEEN,CONNECTION_TYPE,CONNECTION_TYPE_NAME
	,TECHNOLOGY,ISP_NAME,IS_ISP,NETWORK_OPERATOR_NAME,MANUFACTURER,MODEL,LOCATION_TYPE,ANDROID_FINGERPRINT
	,NETWORK_OPERATOR,BRAND,DEVICE,HARDWARE,BUILD_ID,PRODUCT,CDMA_CELL_ID,GSM_CELL_ID,SIM_NETWORK_OPERATOR_NAME
	,SIM_NETWORK_OPERATOR_CODE,ISO_COUNTRY_CODE,MOBILE_COUNTRY_CODE,MOBILE_NETWORK_CODE,VERSION
	,HARDWARE_VERSION,FIRMWARE_VERSION,DEVICE_NAME,CONNECTION_TYPE2,CONNECTION_TYPE_NAME2,TECHNOLOGY2
	,CDMADBM,CDMAECIO,EBDODBM,EVDOECIO,EVDOSNR,GSMBITERRORRATE,GSMSIGNALSTRENGTH
	)
	SELECT	'Android' AS OS
	,	TEST_ID
	,	ANDROID_DEVICE_ID AS DEVICE_ID
	,	TEST_DATE
	,	CLIENT_IP_ADDRESS
	,	DOWNLOAD_KBPS
	,	UPLOAD_KBPS
	,	LATENCY
	,	SERVER_NAME
	,	SERVER_COUNTRY
	,	SERVER_COUNTRY_CODE
	,	SERVER_LATITUDE
	,	SERVER_LONGITUDE
	,	SERVER_SPONSOR_NAME
	,	CLIENT_COUNTRY
	,	CLIENT_COUNTRY_CODE
	,	CLIENT_REGION_NAME
	,	CLIENT_REGION_CODE
	,	CLIENT_CITY
	,	CLIENT_LATITUDE
	,	CLIENT_LONGITUDE
	,	MILES_BETWEEN
	,	CONNECTION_TYPE
	,	CASE	CONNECTION_TYPE WHEN 0 THEN 'UNKNOWN'
					WHEN 1 THEN 'CELL'
					WHEN 2 THEN 'WIFI'
					WHEN 3 THEN 'GPRS'
					WHEN 4 THEN 'EDGE'
					WHEN 5 THEN 'UMTS'
					WHEN 6 THEN 'CDMA'
					WHEN 7 THEN 'EVDO0'
					WHEN 8 THEN 'EVDOA'
					WHEN 9 THEN 'ONEXRTT'
					WHEN 10 THEN 'HSDPA'
					WHEN 11 THEN 'HSPA'
					WHEN 12 THEN 'IDEN'
					WHEN 13 THEN 'EHRPD'
					WHEN 14 THEN 'EVDOB'
					WHEN 15 THEN 'LTE'
					WHEN 16 THEN 'HSUPA'
					WHEN 17 THEN 'HSPAP'
			ELSE 'UNKNOWN'
		END AS CONNECTION_TYPE_NAME
	,	Case	WHEN	CONNECTION_TYPE=0			THEN 'UNKNOWN'
			WHEN	CONNECTION_TYPE in (1,2)		THEN 'WIFI/CELL'
			WHEN	CONNECTION_TYPE in (3,4)		THEN '2G'
			WHEN	CONNECTION_TYPE=15			THEN '4G'
			WHEN	CONNECTION_TYPE between 5 and 17	THEN '3G'
			ELSE	'UNKNOWN'
		END AS TECHNOLOGY
	,	ISP_NAME
	,	IS_ISP
	,	NETWORK_OPERATOR_NAME
	,	MANUFACTURER
	,	MODEL
	,	LOCATION_TYPE
	,	ANDROID_FINGERPRINT
	,	NETWORK_OPERATOR
	,	BRAND
	,	DEVICE
	,	HARDWARE
	,	BUILD_ID
	,	PRODUCT
	,	CDMA_CELL_ID
	,	GSM_CELL_ID
	,	SIM_NETWORK_OPERATOR_NAME
	,	SIM_NETWORK_OPERATOR_CODE
	,	'' AS ISO_COUNTRY_CODE
	,	'' AS MOBILE_COUNTRY_CODE
	,	'' AS MOBILE_NETWORK_CODE
	,	'' AS VERSION
	,	'' AS HARDWARE_VERSION
	,	'' AS FIRMWARE_VERSION
	,	'' AS DEVICE_NAME
	,	PRE_CONNECTION_TYPE AS CONNECTION_TYPE2
	, 	CASE	PRE_CONNECTION_TYPE WHEN 0 THEN 'UNKNOWN'
					WHEN 1 THEN 'CELL'
					WHEN 2 THEN 'WIFI'
					WHEN 3 THEN 'GPRS'
					WHEN 4 THEN 'EDGE'
					WHEN 5 THEN 'UMTS'
					WHEN 6 THEN 'CDMA'
					WHEN 7 THEN 'EVDO0'
					WHEN 8 THEN 'EVDOA'
					WHEN 9 THEN 'ONEXRTT'
					WHEN 10 THEN 'HSDPA'
					WHEN 11 THEN 'HSPA'
					WHEN 12 THEN 'IDEN'
					WHEN 13 THEN 'EHRPD'
					WHEN 14 THEN 'EVDOB'
					WHEN 15 THEN 'LTE'
					WHEN 16 THEN 'HSUPA'
					WHEN 17 THEN 'HSPAP'
			ELSE 'UNKNOWN'
		END AS CONNECTION_TYPE_NAME2
	,	CASE	WHEN	PRE_CONNECTION_TYPE=0			THEN 'UNKNOWN'
			WHEN	PRE_CONNECTION_TYPE IN (1,2)		THEN 'WIFI/CELL'
			WHEN	PRE_CONNECTION_TYPE IN (3,4)		THEN '2G'
			WHEN	PRE_CONNECTION_TYPE=15			THEN '4G'
			WHEN	PRE_CONNECTION_TYPE BETWEEN 5 AND 17	THEN '3G'
			ELSE	'UNKNOWN'
		END AS TECHNOLOGY2
	,	SUBSTR(SIGNAL,1,INSTR(SIGNAL,',',1,1) -1)							AS CDMADBM
	,	SUBSTR(SIGNAL,INSTR(SIGNAL,',',1,1) +1,INSTR(SIGNAL,',',1,2 ) - INSTR(SIGNAL,',',1,1) -1)	AS CDMAECIO
	,	SUBSTR(SIGNAL,INSTR(SIGNAL,',',1,2) +1,INSTR(SIGNAL,',',1,3 ) - INSTR(SIGNAL,',',1,2) -1)	AS EBDODBM
	,	SUBSTR(SIGNAL,INSTR(SIGNAL,',',1,3) +1,INSTR(SIGNAL,',',1,4 ) - INSTR(SIGNAL,',',1,3) -1)	AS EVDOECIO
	,	SUBSTR(SIGNAL,INSTR(SIGNAL,',',1,4) +1,INSTR(SIGNAL,',',1,5 ) - INSTR(SIGNAL,',',1,4) -1)	AS EVDOSNR
	,	SUBSTR(SIGNAL,INSTR(SIGNAL,',',1,5) +1,INSTR(SIGNAL,',',1,6 ) - INSTR(SIGNAL,',',1,5) -1)	AS GSMBITERRORRATE
	,	SUBSTR(SIGNAL,INSTR(SIGNAL,',',1,6) +1)								AS GSMSIGNALSTRENGTH
	FROM PI_OOKLA_ANDROID_DATA
UNION
	SELECT	'iOS' AS OS
	,	TEST_ID
	,	IPHONE_DEVICE_ID AS DEVICE_ID
	,	TEST_DATE
	,	CLIENT_IP_ADDRESS
	,	DOWNLOAD_KBPS
	,	UPLOAD_KBPS
	,	LATENCY
	,	SERVER_NAME
	,	SERVER_COUNTRY
	,	SERVER_COUNTRY_CODE
	,	SERVER_LATITUDE
	,	SERVER_LONGITUDE
	,	SERVER_SPONSOR_NAME
	,	CLIENT_COUNTRY
	,	CLIENT_COUNTRY_CODE
	,	CLIENT_REGION_NAME
	,	CLIENT_REGION_CODE
	,	CLIENT_CITY
	,	CLIENT_LATITUDE
	,	CLIENT_LONGITUDE
	,	MILES_BETWEEN
	,	CONNECTION_TYPE
	,	CASE	CONNECTION_TYPE	WHEN 0 THEN 'UNKNOWN'
					WHEN 1 THEN 'CELL'
					WHEN 2 THEN 'WIFI'
					WHEN 3 THEN 'GPRS'
					WHEN 4 THEN 'EDGE'
					WHEN 5 THEN 'WCDMA'
					WHEN 6 THEN 'HSDPA'
					WHEN 7 THEN 'HSUPA'
					WHEN 8 THEN 'CDMA1x'
					WHEN 9 THEN 'CDMAEVDORev0'
					WHEN 10 THEN 'CDMAEVDORevB'
					WHEN 11 THEN 'eHRPD'
					WHEN 12 THEN 'LTE'
			ELSE 'UNKNOWN'
		END AS CONNECTION_TYPE_NAME
	,	Case	WHEN CONNECTION_TYPE=0 THEN 'UNKNOWN'
			WHEN CONNECTION_TYPE in (1,2) THEN 'WIFI/CELL'
			WHEN CONNECTION_TYPE in (3,4) THEN '2G'
			WHEN CONNECTION_TYPE between 5 and 11 THEN '3G'
			WHEN CONNECTION_TYPE=12 THEN  '4G'
			ELSE 'UNKNOWN'
		END AS TECHNOLOGY
	,	ISP_NAME
	,	IS_ISP
	,	CARRIER_NAME AS NETWORK_OPERATOR_NAME
	,	'Apple' AS MANUFACTURER
	,	MODEL
	,	LOCATION_TYPE
	,	'' AS ANDROID_FINGERPRINT
	,	'' AS NETWORK_OPERATOR
	,	'' AS BRAND
	,	'' AS DEVICE
	,	'' AS HARDWARE
	,	'' AS BUILD_ID
	,	'' AS PRODUCT
	,	'' AS CDMA_CELL_ID
	,	'' AS GSM_CELL_ID
	,	'' AS SIM_NETWORK_OPERATOR_NAME
	,	'' AS SIM_NETWORK_OPERATOR_CODE
	,	ISO_COUNTRY_CODE
	,	MOBILE_COUNTRY_CODE
	,	MOBILE_NETWORK_CODE
	,	VERSION
	,	'' AS HARDWARE_VERSION
	,	'' AS FIRMWARE_VERSION
	,	'' AS DEVICE_NAME
	,	POST_CONNECTION_TYPE AS CONNECTION_TYPE2
	,	CASE	POST_CONNECTION_TYPE	WHEN 0 THEN 'UNKNOWN'
					WHEN 1 THEN 'CELL'
					WHEN 2 THEN 'WIFI'
					WHEN 3 THEN 'GPRS'
					WHEN 4 THEN 'EDGE'
					WHEN 5 THEN 'WCDMA'
					WHEN 6 THEN 'HSDPA'
					WHEN 7 THEN 'HSUPA'
					WHEN 8 THEN 'CDMA1x'
					WHEN 9 THEN 'CDMAEVDORev0'
					WHEN 10 THEN 'CDMAEVDORevB'
					WHEN 11 THEN 'eHRPD'
					WHEN 12 THEN 'LTE'
			ELSE 'UNKNOWN'
		END AS CONNECTION_TYPE_NAME2
	,	Case	WHEN POST_CONNECTION_TYPE=0 THEN 'UNKNOWN'
			WHEN POST_CONNECTION_TYPE in (1,2) THEN 'WIFI/CELL'
			WHEN POST_CONNECTION_TYPE in (3,4) THEN '2G'
			WHEN POST_CONNECTION_TYPE between 5 and 11 THEN '3G'
			WHEN POST_CONNECTION_TYPE=12 THEN  '4G'
			ELSE 'UNKNOWN'
		END AS TECHNOLOGY2
	,	''	AS CDMADBM
	,	''	AS CDMAECIO
	,	''	AS EBDODBM
	,	''	AS EVDOECIO
	,	''	AS EVDOSNR
	,	''	AS GSMBITERRORRATE
	,	''	AS GSMSIGNALSTRENGTH
	FROM	PI_OOKLA_IPHONE_DATA
UNION
	SELECT	'Windows' AS OS
	,	TEST_ID
	,	DEVICE_ID
	,	TEST_DATE
	,	CLIENT_IP_ADDRESS
	,	DOWNLOAD_KBPS
	,	UPLOAD_KBPS
	,	LATENCY
	,	SERVER_NAME
	,	SERVER_COUNTRY
	,	SERVER_COUNTRY_CODE
	,	SERVER_LATITUDE
	,	SERVER_LONGITUDE
	,	SERVER_SPONSOR_NAME
	,	CLIENT_COUNTRY
	,	CLIENT_COUNTRY_CODE
	,	CLIENT_REGION_NAME
	,	CLIENT_REGION_CODE
	,	CLIENT_CITY
	,	CLIENT_LATITUDE
	,	CLIENT_LONGITUDE
	,	MILES_BETWEEN
	,	CONNECTION_TYPE
	,	CASE	CONNECTION_TYPE WHEN 0 THEN 'UNKNOWN'
					WHEN 1 THEN 'CELL'
					WHEN 2 THEN 'WIFI'
					WHEN 3 THEN 'GPRS'
					WHEN 4 THEN '1XRTT'
					WHEN 5 THEN 'EVDO'
					WHEN 6 THEN 'EDGE'
					WHEN 7 THEN '3G'
					WHEN 8 THEN 'HSPA'
					WHEN 9 THEN 'EVDV'
					WHEN 10 THEN 'PassThru'
					WHEN 11 THEN 'LTE'
					WHEN 12 THEN 'EHRPD'
			ELSE 'UNKNOWN'
		END AS CONNECTION_TYPE_NAME
	,	Case	WHEN CONNECTION_TYPE=0			THEN 'UNKNOWN'
			WHEN CONNECTION_TYPE in (1,2)		THEN 'WIFI/CELL'
			WHEN CONNECTION_TYPE in (3,6)		THEN '2G'
			WHEN CONNECTION_TYPE=11			THEN '4G'
			WHEN CONNECTION_TYPE between 4  and 12	THEN '3G'
			ELSE 'UNKNOWN'
		END AS TECHNOLOGY
	,	ISP_NAME
	,	IS_ISP
	,	CARRIER_NAME AS NETWORK_OPERATOR_NAME
	,	MANUFACTURER
	,	'Unknown' AS MODEL
	,	LOCATION_TYPE
	,	'' AS ANDROID_FINGERPRINT
	,	'' AS NETWORK_OPERATOR
	,	'' AS BRAND
	,	'' AS DEVICE
	,	'' AS HARDWARE
	,	'' AS BUILD_ID
	,	'' AS PRODUCT
	,	'' AS CDMA_CELL_ID
	,	'' AS GSM_CELL_ID
	,	'' AS SIM_NETWORK_OPERATOR_NAME
	,	'' AS SIM_NETWORK_OPERATOR_CODE
	,	'' AS ISO_COUNTRY_CODE
	,	'' AS MOBILE_COUNTRY_CODE
	,	'' AS MOBILE_NETWORK_CODE
	,	'' AS VERSION
	,	HARDWARE_VERSION
	,	FIRMWARE_VERSION
	,	DEVICE_NAME
	,	NULL AS CONNECTION_TYPE2
	,	'' AS CONNECTION_TYPE_NAME2
	,	''AS TECHNOLOGY2
	,	''	AS CDMADBM
	,	''	AS CDMAECIO
	,	''	AS EBDODBM
	,	''	AS EVDOECIO
	,	''	AS EVDOSNR
	,	''	AS GSMBITERRORRATE
	,	''	AS GSMSIGNALSTRENGTH
	FROM	PI_OOKLA_WP_DATA
	;