-- data loaded from tmp
COPY PI_OOKLA_IPHONE_DATA
FROM '/tmp/iphone_2014-10-17.psv'
WITH DELIMITER '|'
CSV HEADER;

-- trema in data
-- type windows1258
COPY PI_OOKLA_ANDROID_DATA
FROM '/tmp/android_2014-10-17.psv'
WITH DELIMITER '|'
ENCODING 'WIN1258'
CSV HEADER;

COPY PI_OOKLA_WP_DATA
FROM '/tmp/wp_2014-10-17.psv'
WITH DELIMITER '|'
CSV HEADER;